import type{GameState,HistoricalEvent,NewsItem,RiskAlert,RoundSummary}from"../types";
export type RevealPhase="IDLE"|"DATE"|"MARKET"|"NEWS"|"EVENTS"|"PORTFOLIO"|"RISK"|"COMPLETE";export type MarketHeat="CALM"|"ACTIVE"|"NERVOUS"|"STRESSED"|"PANIC";export type PresentationPriority="NORMAL"|"IMPORTANT"|"BREAKING"|"CRISIS"|"SYSTEMIC";
export interface MarketMover{assetId:string;change:number;from:number;to:number}export interface RoundRevealState{phase:RevealPhase;startedAt:number;currentStep:number;totalSteps:number;isSkipping:boolean;isCrisis:boolean;newNewsIds:string[];newEventIds:string[];newRiskAlertIds:string[];portfolioBefore:number;portfolioAfter:number;marketMovers:MarketMover[]}
export const REVEAL_PHASES:RevealPhase[]=["DATE","MARKET","NEWS","EVENTS","PORTFOLIO","RISK","COMPLETE"];
export function createRoundReveal(before:GameState,after:GameState,summary:RoundSummary,isCrisis=false):RoundRevealState{const movers=Object.entries(after.marketState.prices).map(([assetId,to])=>({assetId,to,from:before.marketState.prices[assetId]??to,change:((to/(before.marketState.prices[assetId]??to))-1)*100})).sort((a,b)=>Math.abs(b.change)-Math.abs(a.change)).slice(0,6);return{phase:"DATE",startedAt:Date.now(),currentStep:0,totalSteps:REVEAL_PHASES.length,isSkipping:false,isCrisis,newNewsIds:summary.newNews.map(n=>n.id),newEventIds:summary.newEvents.map(e=>e.id),newRiskAlertIds:summary.newRiskAlerts.map(a=>a.id),portfolioBefore:before.portfolioValue,portfolioAfter:after.portfolioValue,marketMovers:movers}}
export function nextReveal(state:RoundRevealState){const i=Math.min(REVEAL_PHASES.length-1,state.currentStep+1);return{...state,currentStep:i,phase:REVEAL_PHASES[i]}}
export const revealAll=(state:RoundRevealState):RoundRevealState=>({...state,phase:"COMPLETE",currentStep:state.totalSteps-1,isSkipping:true});
export function newsPriority(news:NewsItem):PresentationPriority{return news.importance>=5?"BREAKING":news.importance>=4?"IMPORTANT":"NORMAL"}export function eventPriority(event:HistoricalEvent):PresentationPriority{return event.severity==="SYSTEMIC"?"SYSTEMIC":event.severity==="CRISIS"?"CRISIS":event.severity==="ELEVATED"?"IMPORTANT":"NORMAL"}
export function marketHeat(state:GameState,events:HistoricalEvent[]=[],news:NewsItem[]=[],alerts:RiskAlert[]=[]):MarketHeat{if(state.marketState.sentiment==="PANIC"||events.some(e=>e.severity==="SYSTEMIC"))return"PANIC";if(events.some(e=>e.severity==="CRISIS")||alerts.some(a=>a.severity==="CRITICAL"))return"STRESSED";if(state.marketState.sentiment==="NEGATIVE"||state.marketState.sentiment==="NERVOUS"||news.length>=3)return"NERVOUS";if(news.length||state.marketState.sentiment==="POSITIVE")return"ACTIVE";return"CALM"}
export function phaseDuration(speed:"NORMAL"|"FAST"|"OFF",crisis=false){if(speed==="OFF")return 0;const base=crisis?700:430;return speed==="FAST"?Math.round(base*.5):base}
