import{describe,expect,it}from"vitest";import{advanceRound,createNewGame,startGame}from"../engine/game-engine";import{createAppSave,migrateToV3,newCareerSave,storeEpisode}from"../campaign/persistence";import{seededInformationState}from"../information/catalog";import{initialRivalState}from"../rivals/catalog";import{closeRoundExperience,createRoundExperience,createRoundSnapshot,getOvernightRisk,getRoundBriefing,transitionRoundExperience}from"./service";
const game=()=>startGame(createNewGame(1928,"great-crash"));
describe("opening and closing bell experience",()=>{
 it("starts a new round in pre-market",()=>expect(createRoundExperience(0)).toMatchObject({phase:"PRE_MARKET",round:0,briefingSeen:false}));
 it("follows the required market session order",()=>{let state=createRoundExperience(0);for(const phase of ["OPENING","TRADING","CLOSING","SUMMARY","OVERNIGHT","PRE_MARKET"]as const){if(phase==="CLOSING"){const result=advanceRound(game()),snapshot=createRoundSnapshot(game(),result.state,result.summary);state=closeRoundExperience(state,snapshot)}else state=transitionRoundExperience(state,phase)}expect(state.phase).toBe("PRE_MARKET")});
 it("rejects invalid transitions",()=>expect(()=>transitionRoundExperience(createRoundExperience(0),"TRADING")).toThrow(/Invalid session transition/));
 it("creates a stable closing snapshot",()=>{const before=game(),result=advanceRound(before),snapshot=createRoundSnapshot(before,result.state,result.summary);expect(snapshot).toMatchObject({round:1,startPortfolioValue:before.portfolioValue,endPortfolioValue:result.state.portfolioValue});expect(snapshot.marketChange).toBeTypeOf("number")});
 it("closes the same processed round idempotently",()=>{const before=game(),result=advanceRound(before),snapshot=createRoundSnapshot(before,result.state,result.summary),closed=closeRoundExperience(createRoundExperience(0,"TRADING"),snapshot);expect(closeRoundExperience(closed,snapshot)).toBe(closed)});
 it("summarizes an empty portfolio without fake positions",()=>{const before=game(),result=advanceRound(before),snapshot=createRoundSnapshot(before,result.state,result.summary);expect(snapshot.bestPosition).toBeUndefined();expect(snapshot.worstPosition).toBeUndefined();expect(snapshot.tradesExecuted).toBe(0)});
 it("calculates round P&L from the before and after portfolio values",()=>{const before=game(),result=advanceRound(before),after={...result.state,portfolioValue:before.portfolioValue+2500},snapshot=createRoundSnapshot(before,after,result.summary);expect(snapshot.portfolioPnL).toBe(2500);expect(snapshot.portfolioReturn).toBeCloseTo(2.5)});
 it("identifies best and worst open positions",()=>{const before=game(),result=advanceRound(before),after={...result.state,positions:[{assetId:"industrials",quantity:10,averageBuyPrice:100,currentPrice:110,marketValue:1100,unrealizedPnL:100,unrealizedPnLPercent:10},{assetId:"railroads",quantity:10,averageBuyPrice:100,currentPrice:95,marketValue:950,unrealizedPnL:-50,unrealizedPnLPercent:-5}]},snapshot=createRoundSnapshot(before,after,result.summary);expect(snapshot.bestPosition?.assetId).toBe("industrials");expect(snapshot.worstPosition?.assetId).toBe("railroads")});
 it("counts trades by side",()=>{const before=game(),trade={id:"t",date:before.currentDate,roundNumber:before.roundNumber,assetId:"industrials",side:"BUY"as const,quantity:1,price:100,grossValue:100,fee:1,netValue:101},traded={...before,tradeHistory:[trade]},result=advanceRound(traded),snapshot=createRoundSnapshot(traded,result.state,result.summary);expect(snapshot.tradesExecuted).toBe(1);expect(snapshot.buys).toBe(1)});
 it("builds briefings from currently available information only",()=>{const save=newCareerSave(),current={...game(),currentDate:"1928-01-01",roundNumber:1},briefing=getRoundBriefing(current,save.investorProfile!.character,seededInformationState(),initialRivalState(1928));expect(briefing.informationIds).not.toContain("rumor-bank-withdrawals");expect(briefing.news.every(x=>x.headline.length>0)).toBe(true)});
 it("does not expose hidden rival activity to a weak character",()=>{const save=newCareerSave(),character={...save.investorProfile!.character,stats:{trading:0,risk:0,information:0,network:0,reputation:0,influence:0},unlockedSkills:[]},rivals=initialRivalState(1928);rivals.activities=[{id:"hidden",round:0,gameDate:"1928-01-01",rivalId:rivals.rivals[0].id,type:"TRADE_INTENT",assetId:"railroads",action:"SHORT",sizeClass:"LARGE",publicVisibility:"HIDDEN",summary:"hidden"}];expect(getRoundBriefing(game(),character,seededInformationState(),rivals).rivalIntelligenceIds).not.toContain("hidden")});
 it("rates an unexposed portfolio as low overnight risk",()=>expect(getOvernightRisk(game(),seededInformationState(),0).level).toBe("LOW"));
 it("increases risk when volatility rises",()=>{const active=game(),info={items:[],lastProcessedRound:-1};expect(getOvernightRisk(active,info,7).level).not.toBe(getOvernightRisk(active,info,0).level)});
 it("counts unresolved high-impact rumors",()=>{const active={...startGame(createNewGame(1906,"panic-1907")),currentDate:"1907-06-01"},information=seededInformationState(),first=information.items[0];information.items.push({...first,id:"second-high-impact-rumor"});const risk=getOvernightRisk(active,information,0);expect(risk.highImpactRumors).toBe(2);expect(risk.level).toBe("MODERATE")});
 it("raises overnight risk for margin, shorts and volatility",()=>{const base=game(),stressed={...base,marginAccount:{...base.marginAccount,marginUtilization:90},shortPositions:[{id:"s",assetId:"railroads",quantity:100,averageEntryPrice:80,currentPrice:80,marketValue:8000,unrealizedPnL:0,realizedPnL:0,borrowFeeAccrued:0,marginRequirement:4000,marginUsed:4000,openedAt:base.currentDate,lastUpdated:base.currentDate}]};expect(["HIGH","EXTREME"]).toContain(getOvernightRisk(stressed,seededInformationState(),9).level)});
 it("preserves an in-progress summary through v3 loading",()=>{const before=game(),result=advanceRound(before),snapshot=createRoundSnapshot(before,result.state,result.summary),save={...createAppSave(),activeEpisode:result.state,roundExperience:transitionRoundExperience(closeRoundExperience(createRoundExperience(0,"TRADING"),snapshot),"SUMMARY")};expect(migrateToV3(save).roundExperience).toEqual(save.roundExperience)});
 it("migrates an older active v3 save directly into trading",()=>{const raw={...createAppSave(),activeEpisode:game()}as Record<string,unknown>;delete raw.roundExperience;expect(migrateToV3(raw).roundExperience?.phase).toBe("TRADING")});
 it("processes rival and information systems only once per round",()=>{const save=newCareerSave(),active=game(),once=storeEpisode(save,active),twice=storeEpisode(once,active);expect(twice.rivals).toEqual(once.rivals);expect(twice.information).toEqual(once.information)});
 it("keeps overnight risk pure",()=>{const active=game(),information=seededInformationState(),before=structuredClone({active,information});getOvernightRisk(active,information,5);expect({active,information}).toEqual(before)});
});


