import{describe,expect,it}from"vitest";import{createNewGame,startGame,recalculateGameState}from"../engine/game-engine";import{executeTrade}from"../trading/service";import{accrueBorrowFees,borrowFeeFor,coverShort,enforceMargin,exposure,marginAccount,openShort,upgradeAdvancedState}from"./service";import{MARKET_RULES}from"./rules";import{TRADING_CALENDAR}from"./calendar";
const game=()=>startGame(createNewGame());
describe("Sprint 5 advanced trading",()=>{
it("opens shorts with restricted proceeds and collateral",()=>{const s=game(),price=s.marketState.prices.banking,n=openShort(s,"banking",100);expect(n.shortPositions[0].quantity).toBe(100);expect(n.marginAccount.restrictedCash).toBeCloseTo(price*100);expect(n.cash).toBeLessThan(s.cash);expect(n.portfolioValue).toBe(s.portfolioValue)});
it("covers partially and fully with correct profitable P&L",()=>{let s=openShort(game(),"banking",100);const entry=s.shortPositions[0].averageEntryPrice;s={...s,marketState:{...s.marketState,prices:{...s.marketState.prices,banking:entry-10}}};s=recalculateGameState(s);const partial=coverShort(s,"banking",40),full=coverShort(partial,"banking",60);expect(partial.shortPositions[0].quantity).toBe(60);expect(full.shortPositions).toHaveLength(0);expect(full.realizedPnL).toBeGreaterThan(0)});
it("models losses beyond initial collateral",()=>{let s=openShort(game(),"banking",100);const entry=s.shortPositions[0].averageEntryPrice;s={...s,marketState:{...s.marketState,prices:{...s.marketState.prices,banking:entry*2}}};s=recalculateGameState(s);expect(s.shortPositions[0].unrealizedPnL).toBeLessThan(-s.shortPositions[0].marginUsed)});
it("accrues borrow fees by day, week, and month",()=>{expect(borrowFeeFor(10000,.05,7)).toBeCloseTo(borrowFeeFor(10000,.05,1)*7);expect(borrowFeeFor(10000,.05,30)).toBeGreaterThan(borrowFeeFor(10000,.05,7));const s=accrueBorrowFees(openShort(game(),"banking",10),30);expect(s.borrowFeesPaid).toBeGreaterThan(0)});
it("calculates gross, net, leverage and margin",()=>{let s=executeTrade(game(),"BUY","industrials",100);s=openShort(s,"banking",50);const x=exposure(s);expect(x.gross).toBeCloseTo(x.long+x.short);expect(x.net).toBeCloseTo(x.long-x.short);expect(marginAccount(s).marginUsed).toBeGreaterThan(0)});
it("creates and ultimately liquidates an unresolved margin call",()=>{let s=openShort(game(),"banking",500);const entry=s.shortPositions[0].averageEntryPrice;s={...s,roundNumber:1,marketState:{...s.marketState,prices:{...s.marketState.prices,banking:entry*4}}};s=enforceMargin(s);expect(s.marginCalls.some(x=>x.status==="OPEN")).toBe(true);s=enforceMargin({...s,roundNumber:2});expect(s.shortPositions).toHaveLength(0);expect(s.forcedCovers).toBe(1)});
it("blocks a new short only while a dated ban is active",()=>{MARKET_RULES.push({id:"test-ban",episodeId:"great-crash",assetId:"banking",effectiveFrom:"1929-09-10",effectiveUntil:"1929-09-20",ruleType:"SHORT_SELLING_BANNED",parameters:{existing:"NO_NEW_SHORTS"},historicalBasis:"Test fixture",dataType:"SIMULATED"});expect(()=>openShort({...game(),currentDate:"1929-09-01"},"banking",1)).not.toThrow();expect(()=>openShort({...game(),currentDate:"1929-09-15"},"banking",1)).toThrow(/RESTRICTED|shortable/);expect(()=>openShort({...game(),currentDate:"1929-09-21"},"banking",1)).not.toThrow();MARKET_RULES.splice(MARKET_RULES.findIndex(x=>x.id==="test-ban"),1)});
it("skips weekends and known closures",()=>{expect(TRADING_CALENDAR.isTradingDay("1929-09-07","great-crash")).toBe(false);expect(TRADING_CALENDAR.nextTradingDay("1929-09-06","great-crash")).toBe("1929-09-09");expect(TRADING_CALENDAR.closureReason("1933-03-06","great-crash")).toContain("bank holiday")});
it("migrates long-only state without changing value",()=>{const s=game(),old={...s}as Partial<typeof s>;delete old.shortPositions;delete old.marginAccount;delete old.marginCalls;delete old.borrowFeesPaid;const n=upgradeAdvancedState(old as typeof s);expect(n.portfolioValue).toBe(s.portfolioValue);expect(n.shortPositions).toEqual([])});
});
