import { exposure } from "../advanced-trading/service";
import type { GameState, TradeSide } from "../types";
import type { AssetPricePoint, ChartRange, CompactPortfolioSnapshot, DecisionOutcome, DecisionReason, DecisionRecord, KnownMarketContext, RoundSummaryRecord } from "./models";

const heat=(state:GameState)=>state.marketState.sentiment==="PANIC"?"PANIC":state.marketState.sentiment==="NEGATIVE"?"STRESSED":state.marketState.sentiment==="NERVOUS"?"NERVOUS":state.marketState.sentiment==="POSITIVE"?"ACTIVE":"CALM";
export function compactPortfolio(state:GameState,id=`portfolio-${state.gameId}-${state.roundNumber}`):CompactPortfolioSnapshot{const x=exposure(state);return{id,portfolioValue:state.portfolioValue,cash:state.cash,longExposure:x.long,shortExposure:x.short,grossExposure:x.gross,netExposure:x.net,marginUtilization:x.marginUtilization}}
export function knownMarketContext(state:GameState,id=`market-${state.gameId}-${state.roundNumber}`):KnownMarketContext{return{id,marketHeat:heat(state),knownRegime:state.marketState.regimeLabel,knownSentiment:state.marketState.sentiment,knownRiskState:state.riskAlerts.at(-1)?.severity??"INFO",knownNewsIds:[...state.seenNews],knownIndicatorIds:[],knownTopSignals:[]}}
export function createDecision(state:GameState,type:TradeSide|"HOLD",input:{assetId?:string;quantity?:number;reason?:DecisionReason;reasonText?:string}={}):DecisionRecord{const before=compactPortfolio(state),market=knownMarketContext(state),price=input.assetId?state.marketState.prices[input.assetId]:undefined;return{id:`decision-${state.gameId}-${state.decisionHistory.length+1}`,actorType:"PLAYER",episodeId:state.episodeId,roundNumber:state.roundNumber,gameDate:state.currentDate,type,status:type==="HOLD"?"HELD":"EXECUTED",assetId:input.assetId,quantity:input.quantity,amount:price&&input.quantity?price*input.quantity:undefined,price,positionDirection:type==="SHORT"||type==="COVER"?"SHORT":type==="BUY"||type==="SELL"?"LONG":undefined,reason:input.reason??(type==="HOLD"?"STRATEGY":"CUSTOM"),reasonText:input.reasonText?.slice(0,240),reasonTags:[],strategyContext:state.strategyProfile.id,marketContextSnapshotId:market.id,portfolioSnapshotBeforeId:before.id,marketContext:market,portfolioBefore:before,createdAt:new Date().toISOString()}}
export function recordHold(state:GameState,reasonText="Maintain current strategy."):GameState{if(state.decisionHistory.some(x=>x.roundNumber===state.roundNumber&&x.type==="HOLD"))return state;return{...state,decisionHistory:[...state.decisionHistory,createDecision(state,"HOLD",{reason:"STRATEGY",reasonText})]}}
export function completeDecision(state:GameState,decision:DecisionRecord,tradeId?:string):GameState{const after=compactPortfolio(state,`portfolio-after-${decision.id}`),record={...decision,tradeId,portfolioSnapshotAfterId:after.id,portfolioAfter:after},next={...state,decisionHistory:[...state.decisionHistory,record],tradeHistory:state.tradeHistory.map(t=>t.id===tradeId?{...t,decisionId:decision.id}:t)};if(decision.type!=="SELL"&&decision.type!=="COVER")return next;const direction=decision.type==="COVER"?"SHORT":"LONG",stillOpen=direction==="SHORT"?next.shortPositions.some(p=>p.assetId===decision.assetId):next.positions.some(p=>p.assetId===decision.assetId),closeOutcome={...evaluateDecision(next,record),status:"CLOSED" as const,frozen:true},entryOutcomes=stillOpen?[]:next.decisionHistory.filter(d=>d.assetId===decision.assetId&&d.positionDirection===direction&&(d.type==="BUY"||d.type==="SHORT")).filter(d=>!next.decisionOutcomes.some(o=>o.decisionId===d.id&&o.frozen)).map(d=>({...evaluateDecision(next,d),status:"CLOSED" as const,frozen:true}));return{...next,decisionOutcomes:[...next.decisionOutcomes,...entryOutcomes,closeOutcome]}}
export function initialPriceHistory(state:GameState):AssetPricePoint[]{return Object.entries(state.marketState.prices).map(([assetId,close])=>({assetId,episodeId:state.episodeId,roundNumber:state.roundNumber,date:state.currentDate,close,dataType:"SIMULATED"}))}
export function appendCurrentPrices(state:GameState):AssetPricePoint[]{const existing=new Set(state.assetPriceHistory.map(p=>`${p.assetId}:${p.roundNumber}`));return[...state.assetPriceHistory,...Object.entries(state.marketState.prices).filter(([assetId])=>!existing.has(`${assetId}:${state.roundNumber}`)).map(([assetId,close])=>({assetId,episodeId:state.episodeId,roundNumber:state.roundNumber,date:state.currentDate,open:state.marketState.previousPrices[assetId],high:Math.max(close,state.marketState.previousPrices[assetId]??close),low:Math.min(close,state.marketState.previousPrices[assetId]??close),close,dataType:"SIMULATED" as const}))]}
export function getAssetHistory(state:GameState,assetId:string,currentDate=state.currentDate){return state.assetPriceHistory.filter(p=>p.assetId===assetId&&p.date<=currentDate).sort((a,b)=>a.roundNumber-b.roundNumber)}
export function getAssetHistoryByRounds(state:GameState,assetId:string,roundCount:number){return getAssetHistory(state,assetId).slice(-Math.max(1,roundCount))}
export function getAssetHistoryByRange(state:GameState,assetId:string,startDate:string,endDate:string){return getAssetHistory(state,assetId,endDate).filter(p=>p.date>=startDate)}
export function getLatestPricePoint(state:GameState,assetId:string){return getAssetHistory(state,assetId).at(-1)}
const rangeRounds=(range:ChartRange)=>range==="1W"?7:range==="1M"?31:range==="3M"?93:range==="1Y"?366:Number.MAX_SAFE_INTEGER;
export function historyForRange(state:GameState,assetId:string,range:ChartRange){const history=getAssetHistory(state,assetId);if(range==="ERA"||history.length<2)return history;const end=new Date(`${state.currentDate}T00:00:00Z`).getTime(),days=rangeRounds(range);return history.filter(p=>end-new Date(`${p.date}T00:00:00Z`).getTime()<=days*86400000)}
export function getEntryRelativePerformance(state:GameState,assetId:string){const long=state.positions.find(p=>p.assetId===assetId),short=state.shortPositions.find(p=>p.assetId===assetId),current=state.marketState.prices[assetId];if(long)return{direction:"LONG" as const,entry:long.averageBuyPrice,current,returnPercent:(current/long.averageBuyPrice-1)*100};if(short)return{direction:"SHORT" as const,entry:short.averageEntryPrice,current,returnPercent:(short.averageEntryPrice/current-1)*100};return undefined}
export function marketMemory(state:GameState,assetId:string,range:ChartRange="ERA"){const points=historyForRange(state,assetId,range),closes=points.map(p=>p.close),current=closes.at(-1)??state.marketState.prices[assetId],era=getAssetHistory(state,assetId),eraCloses=era.map(p=>p.close),eraHigh=Math.max(...eraCloses),eraLow=Math.min(...eraCloses),periodHigh=Math.max(...closes),periodLow=Math.min(...closes),entry=getEntryRelativePerformance(state,assetId);return{current,eraHigh,eraLow,periodHigh,periodLow,drawdownFromEraHigh:eraHigh?(current/eraHigh-1)*100:0,returnSinceEraStart:era[0]?(current/era[0].close-1)*100:0,entry}}
export function evaluateDecision(state:GameState,decision:DecisionRecord):DecisionOutcome{const current=decision.assetId?state.marketState.prices[decision.assetId]:undefined,elapsed=state.roundNumber-decision.roundNumber,fees=decision.tradeId?state.tradeHistory.find(t=>t.id===decision.tradeId)?.fee??0:0,short=decision.positionDirection==="SHORT",gross=decision.price&&current&&decision.quantity?(short?decision.price-current:current-decision.price)*decision.quantity:0,borrow=short&&decision.assetId?state.shortPositions.find(p=>p.assetId===decision.assetId)?.borrowFeeAccrued??0:0,net=gross-fees-borrow,positionOpen=decision.assetId?(short?state.shortPositions.some(p=>p.assetId===decision.assetId):state.positions.some(p=>p.assetId===decision.assetId)):false,closed=(decision.type==="SELL"||decision.type==="COVER")||Boolean(decision.assetId&&!positionOpen&&elapsed>0),status=closed?"CLOSED":net>0?"POSITIVE":net<0?"NEGATIVE":decision.type==="HOLD"?"NEUTRAL":"OPEN";return{id:`outcome-${decision.id}-${state.roundNumber}`,decisionId:decision.id,evaluationRound:state.roundNumber,evaluationDate:state.currentDate,roundsElapsed:elapsed,assetPriceAtDecision:decision.price,assetPriceNow:current,grossPnL:gross,positionPnL:gross,fees,borrowFees:borrow,netPnL:net,portfolioImpact:state.portfolioValue-decision.portfolioBefore.portfolioValue,status,frozen:closed}}
export function updateDecisionOutcomes(state:GameState){const frozen=new Set(state.decisionOutcomes.filter(x=>x.frozen).map(x=>x.decisionId)),horizons=new Set([1,3,5,10]);const additions=state.decisionHistory.filter(d=>!frozen.has(d.id)).map(d=>evaluateDecision(state,d)).filter(o=>horizons.has(o.roundsElapsed)||o.frozen);return[...state.decisionOutcomes,...additions.filter(x=>!state.decisionOutcomes.some(old=>old.id===x.id))]}
export function latestOutcome(state:GameState,decisionId:string){return state.decisionOutcomes.filter(x=>x.decisionId===decisionId).at(-1)??evaluateDecision(state,state.decisionHistory.find(x=>x.id===decisionId)!)}
export function roundRecord(before:GameState,after:GameState):RoundSummaryRecord{const decisions=before.decisionHistory.filter(d=>d.roundNumber===before.roundNumber),longPnL=after.positions.reduce((n,p)=>n+p.unrealizedPnL,0)-before.positions.reduce((n,p)=>n+p.unrealizedPnL,0),shortPnL=after.shortPositions.reduce((n,p)=>n+p.unrealizedPnL,0)-before.shortPositions.reduce((n,p)=>n+p.unrealizedPnL,0),pnl=after.portfolioValue-before.portfolioValue;return{roundNumber:after.roundNumber,date:after.currentDate,portfolioStart:before.portfolioValue,portfolioEnd:after.portfolioValue,pnl,return:before.portfolioValue?pnl/before.portfolioValue*100:0,longPnL,shortPnL,fees:before.tradeHistory.filter(t=>t.roundNumber===before.roundNumber).reduce((n,t)=>n+t.fee,0),borrowFees:after.borrowFeesPaid-before.borrowFeesPaid,cashChange:after.cash-before.cash,decisionIds:decisions.map(d=>d.id)}}
