import{createCharacter}from"../character-foundation/service";import type{CharacterArchetypeId,CharacterSkillId,CharacterTraitId,CharacterWeaknessId}from"../character-foundation/models";import type{RivalInvestor,RivalState,RivalStrategyDefinition,RivalStrategyId}from"./models";
export const RIVAL_STRATEGIES:RivalStrategyDefinition[]=[
 {id:"MOMENTUM",name:"Momentum",preferredAssets:["railroads","industrials"],riskBias:78,patience:25,shortBias:75,informationDependence:45,sentimentBias:70},
 {id:"VALUE",name:"Value",preferredAssets:["industrials","banking"],riskBias:42,patience:90,shortBias:15,informationDependence:70,sentimentBias:-30},
 {id:"CRISIS",name:"Crisis",preferredAssets:["banking","gold"],riskBias:70,patience:35,shortBias:65,informationDependence:65,sentimentBias:-60},
 {id:"NETWORK",name:"Network",preferredAssets:["banking","industrials"],riskBias:55,patience:50,shortBias:35,informationDependence:95,sentimentBias:10},
 {id:"BANKING",name:"Banking",preferredAssets:["banking","bonds"],riskBias:35,patience:70,shortBias:10,informationDependence:80,sentimentBias:-10},
 {id:"CORPORATE_CONTROL",name:"Corporate Control",preferredAssets:["industrials","railroads"],riskBias:72,patience:75,shortBias:5,informationDependence:60,sentimentBias:20}
];
type Seed={id:string;name:string;historical:boolean;from:number;until?:number;archetype:CharacterArchetypeId;traits:[CharacterTraitId,CharacterTraitId];weakness:CharacterWeaknessId;skills:CharacterSkillId[];strategy:RivalStrategyId;risk:number;objective:RivalInvestor["objectives"][number]};
const seeds:Seed[]=[
 {id:"jesse-livermore",name:"Jesse Livermore",historical:true,from:1900,until:1940,archetype:"SPECULATOR",traits:["TAPE_READER","FAST_OPERATOR"],weakness:"OVERCONFIDENT",skills:["TAPE_READER_I","SHORT_SPECIALIST"],strategy:"MOMENTUM",risk:84,objective:{id:"livermore-short",description:"Build a major short position",type:"BUILD_SHORT",weight:8}},
 {id:"jp-morgan",name:"J. P. Morgan",historical:true,from:1900,until:1913,archetype:"BANKER",traits:["NETWORK_BUILDER","NEGOTIATOR"],weakness:"REPUTATION_SENSITIVE",skills:["BANKER_CONTACTS","TRUSTED_OPERATOR"],strategy:"BANKING",risk:35,objective:{id:"morgan-banks",description:"Support banking-sector stability",type:"BANKING_EXPOSURE",weight:7}},
 {id:"benjamin-graham",name:"Benjamin Graham",historical:true,from:1926,until:1976,archetype:"VALUE_INVESTOR",traits:["DEEP_RESEARCH","CONTRARIAN"],weakness:"RISK_AVERSE",skills:["SOURCE_EVALUATION","DEEP_RESEARCH_SKILL"],strategy:"VALUE",risk:32,objective:{id:"graham-preserve",description:"Preserve capital while accumulating value",type:"PRESERVE_CAPITAL",weight:8}},
 {id:"evelyn-cross",name:"Evelyn Cross",historical:false,from:1900,archetype:"CORPORATE_RAIDER",traits:["NEGOTIATOR","CALCULATED_RISK"],weakness:"LEVERAGE_HABIT",skills:["OFFICE_MANAGEMENT","INDUSTRIAL_CONNECTIONS"],strategy:"CORPORATE_CONTROL",risk:76,objective:{id:"cross-industry",description:"Accumulate industrial control positions",type:"ACCUMULATE_INDUSTRY",weight:7}},
 {id:"samuel-vale",name:"Samuel Vale",historical:false,from:1900,archetype:"NETWORKER",traits:["NETWORK_BUILDER","DEEP_RESEARCH"],weakness:"INFORMATION_ADDICT",skills:["SOURCE_EVALUATION","BANKER_CONTACTS","PRESS_NETWORK"],strategy:"NETWORK",risk:55,objective:{id:"vale-reputation",description:"Increase market reputation",type:"REPUTATION",weight:5}},
 {id:"clara-voss",name:"Clara Voss",historical:false,from:1900,archetype:"CRISIS_TRADER",traits:["CONTRARIAN","MARKET_HISTORIAN"],weakness:"IMPATIENT",skills:["CRISIS_DISCIPLINE","MARGIN_DISCIPLINE"],strategy:"CRISIS",risk:72,objective:{id:"voss-crisis",description:"Profit from crisis dislocation",type:"CRISIS_PROFIT",weight:8}}
];
export function createRival(seed:Seed):RivalInvestor{const base=createCharacter({id:`rival-character-${seed.id}`,actorType:seed.historical?"HISTORICAL_RIVAL":"FICTIONAL_RIVAL",name:seed.name,avatar:`rival-${seed.id}`,archetype:seed.archetype,traits:seed.traits,weakness:seed.weakness,level:4,xp:0});return{id:seed.id,historical:seed.historical,availableFromYear:seed.from,availableUntilYear:seed.until,character:{...base,unlockedSkills:seed.skills},strategy:seed.strategy,capital:100000,cash:100000,positions:[],riskTolerance:seed.risk,confidence:55,objectives:[seed.objective],knowledge:{knownInformationIds:[],investigatedInformationIds:[],confidenceByInformationId:{}},status:"WATCHING"}}
export const RIVAL_CATALOG=seeds.map(createRival);export const initialRivalState=(year=1900):RivalState=>({rivals:RIVAL_CATALOG.filter(x=>isRivalAvailableInEra(x,year)).map(x=>structuredClone(x)),activities:[],lastProcessedRound:-1});export function isRivalAvailableInEra(rival:RivalInvestor,year:number){return year>=rival.availableFromYear&&year<=(rival.availableUntilYear??9999)}
