import { describe, expect, it } from "vitest";
import { createAppSave, newCareerSave } from "../campaign/persistence";
import { createNewGame, startGame } from "../engine/game-engine";
import { createRoundExperience } from "../round-experience/service";
import type { RoundSnapshot } from "../round-experience/models";
import type { GameExperienceEvent } from "./models";
import { actionTarget, getIntraRoundEventSchedule, getOfficeActivities, getPendingSessionEvents, getRoundExperienceEvents, getRoundStory } from "./service";

const setup=()=>{const save=newCareerSave(),game=startGame(createNewGame(1928,"great-crash",100000));return{save:{...save,activeEpisode:game,roundExperience:createRoundExperience(game.roundNumber)},game}};

describe("game experience director",()=>{
 it("is deterministic and selects one highest-priority hero",()=>{const{save,game}=setup(),a=getRoundExperienceEvents(save,game),b=getRoundExperienceEvents(save,game);expect(a).toEqual(b);expect(a.hero).toBeDefined();expect(["CRITICAL","MAJOR","STANDARD","AMBIENT"]).toContain(a.hero.priority)});
 it("does not use future information",()=>{const{save,game}=setup(),future={...save.information.items[0],id:"future-private",title:"FUTURE SECRET",availableFromDate:"1935-01-01",createdRound:999,status:"ACQUIRED"as const},events=getRoundExperienceEvents({...save,information:{...save.information,items:[future]}},game);expect(JSON.stringify(events)).not.toContain("FUTURE SECRET")});
 it("does not leak hidden rival activity",()=>{const{save,game}=setup(),hidden={id:"hidden-rival",round:0,gameDate:game.currentDate,rivalId:save.rivals.rivals[0].id,type:"TRADE_INTENT"as const,assetId:"railroads",action:"SHORT"as const,sizeClass:"LARGE"as const,publicVisibility:"HIDDEN"as const,summary:"SECRET SHORT"},events=getRoundExperienceEvents({...save,rivals:{...save.rivals,activities:[hidden]}},game);expect(JSON.stringify(events)).not.toContain("SECRET SHORT")});
 it("creates a stable, unique session schedule",()=>{const{save,game}=setup(),a=getIntraRoundEventSchedule(save,game);expect(a).toEqual(getIntraRoundEventSchedule(save,game));expect(new Set(a.map(x=>x.id)).size).toBe(a.length);expect(a.every(x=>x.secondsRemaining>0&&x.secondsRemaining<60)).toBe(true)});
 it("schedules only during trading and never repeats triggered events",()=>{const{save,game}=setup(),schedule=getIntraRoundEventSchedule(save,game);expect(getIntraRoundEventSchedule(save,game,"OPENING")).toEqual([]);expect(getPendingSessionEvents(schedule,[schedule[0].id])).not.toContainEqual(schedule[0])});
 it("routes investigation, market, rival and deal actions through existing screens",()=>{const base:GameExperienceEvent={id:"x",priority:"MAJOR",source:"INFORMATION",title:"x",summary:"x",detail:"x",upside:"MODERATE",risk:"MODERATE",reputationExposure:"LOW",actions:[{id:"INVESTIGATE",label:"Investigate",target:"INFORMATION"},{id:"VIEW_MARKET",label:"Trade",target:"MARKET"},{id:"VIEW_RIVAL",label:"Rival",target:"RIVALS"},{id:"ACCEPT_DEAL",label:"Deal",target:"DEALS"}]};expect(actionTarget(base,"INVESTIGATE")).toBe("INFORMATION");expect(actionTarget(base,"VIEW_MARKET")).toBe("MARKET");expect(actionTarget(base,"VIEW_RIVAL")).toBe("RIVALS");expect(actionTarget(base,"ACCEPT_DEAL")).toBe("DEALS")});
 it("derives office badges from current session state",()=>{const{save,game}=setup(),activities=getOfficeActivities(save,game);expect(activities.some(x=>x.zone==="MARKET_BOARD")).toBe(true);expect(activities.every(x=>x.count>0)).toBe(true)});
 it("builds a prioritized story only from the recorded snapshot",()=>{const{save,game}=setup(),snapshot={round:1,date:"1928-02-01",startPortfolioValue:100000,endPortfolioValue:95000,startCash:100000,endCash:80000,portfolioPnL:-5000,portfolioReturn:-5,tradesExecuted:1,buys:0,sells:0,shorts:1,covers:0,marketChange:-6,riskAlerts:1,importantNews:["Selling wave strikes exchange"],rivalActivityIds:["visible-1"],informationChanges:[],summary:{roundNumber:1,date:"1928-02-01",portfolioValue:95000,weeklyChange:-5,cash:80000,cashChange:-20000,sentiment:"PANIC"as const,newEvents:[],newNews:[],newRiskAlerts:[],strategyViolationCount:0}} satisfies RoundSnapshot,story=getRoundStory({...save,roundExperience:{...createRoundExperience(1,"SUMMARY"),snapshot}},game);expect(story.newspaperTitle).toBe("MARKETS PLUNGE");expect(story.sentences.length).toBeLessThanOrEqual(5);expect(story.sentences.join(" ")).toContain("Selling wave")});
 it("has a safe fallback for an empty save",()=>{const save=createAppSave(),game=startGame(createNewGame(1907,"panic-1907",100000));const events=getRoundExperienceEvents(save,game);expect(events.hero).toBeDefined();expect(events.hero.actions.length).toBeGreaterThan(0)});
});
