import type{ActivePerk,ArchetypeDefinition,AvatarDefinition,MentorDefinition}from"./models";
const ability=(id:string,name:string,category:ArchetypeDefinition["coreAbility"]["category"],effectType:ArchetypeDefinition["coreAbility"]["effectType"],description:string,tradeoff:string)=>({id,name,category,effectType,description,effectConfig:{weight:1},conditions:["Only already-known information"],tradeoffs:[tradeoff]});
export const AVATARS:AvatarDefinition[]=[
...[["male-industrialist-01","Industrial Classic","1900s","senior tailored"],["male-banker-01","Banking Modern","1920s","young formal"],["male-value-01","Value Scholar","1940s","mature academic"],["male-macro-01","Macro Diplomat","1970s","midcareer international"],["male-risk-01","Risk Steward","1990s","senior understated"],["male-growth-01","Growth Founder","Modern","young contemporary"]].map(x=>({id:x[0],name:x[1],genderPresentation:"MALE" as const,portraitAsset:`/avatars/${x[0]}.webp`,eraStyle:x[2],visualTags:x[3].split(" "),isStarter:true})),
...[["female-industrialist-01","Industrial Pioneer","1900s","mature tailored"],["female-banker-01","Credit Strategist","1920s","senior formal"],["female-value-01","Value Scholar","1940s","midcareer academic"],["female-macro-01","Macro Diplomat","1970s","young international"],["female-risk-01","Risk Steward","1990s","mature understated"],["female-growth-01","Growth Founder","Modern","young contemporary"]].map(x=>({id:x[0],name:x[1],genderPresentation:"FEMALE" as const,portraitAsset:`/avatars/${x[0]}.webp`,eraStyle:x[2],visualTags:x[3].split(" "),isStarter:true}))];
export const ARCHETYPES:ArchetypeDefinition[]=[
["INDUSTRIALIST","THE INDUSTRIALIST","Industry & commodities","DEEP INDUSTRY NETWORK","INFORMATION","PRIORITY_BOOST","Industry context receives higher display priority.","Less tactical market detail","COMMODITY"],
["BANKER","THE BANKER","Credit & liquidity","CREDIT NETWORK","RISK","ALERT_DETAIL","Known banking stress receives prominent detail.","Less sector opportunity detail","RISK"],
["VALUE_INVESTOR","THE VALUE INVESTOR","Quality & preservation","MARGIN OF SAFETY","STRATEGY","STRATEGY_EXPLANATION","Capital preservation context is expanded.","Less momentum emphasis","STRATEGY"],
["SPECULATOR","THE SPECULATOR","Momentum & volatility","READ THE TAPE","MARKET","EXTRA_CONTEXT","Market tape details are expanded.","Tactical data receives priority","MARKET"],
["MACRO_STRATEGIST","THE MACRO STRATEGIST","Rates & growth","BIG PICTURE","MACRO","RESEARCH_DETAIL","Cross-indicator relationships are expanded.","Less single-company detail","MACRO"],
["CRISIS_INVESTOR","THE CRISIS INVESTOR","Panic & liquidity","STAY CALM","CRISIS","EXTRA_SCENARIO","Crisis mode gains one scenario slot.","Normal markets get little benefit","RISK"],
["COMMODITY_TRADER","THE COMMODITY TRADER","Real assets","REAL ASSETS","COMMODITY","EXTRA_CONTEXT","Commodity cross-asset context is expanded.","Less equity detail","COMMODITY"],
["RISK_OFFICER","THE RISK OFFICER","Exposure & drawdown","RISK DISCIPLINE","RISK","EXTRA_SCENARIO","One additional portfolio scenario is available.","Opportunity detail receives less priority","RISK"],
["GROWTH_INVESTOR","THE GROWTH INVESTOR","Innovation & growth","NEW FRONTIERS","RESEARCH","PRIORITY_BOOST","Known innovation news receives higher priority.","Less defensive context","NEWS"],
["MARKET_HISTORIAN","THE MARKET HISTORIAN","Patterns & structure","HISTORICAL LENS","HISTORY","RESEARCH_DETAIL","Unlocked historical context is easier to find.","No predictive advantage","NEWS"]
].map(x=>({id:x[0],name:x[1],focus:[x[2]],coreAbility:ability(`${x[0]}-CORE`,x[3],x[4] as never,x[5] as never,x[6],x[7]),secondaryStrength:x[2],tradeoff:x[7],preferredAgent:x[8] as never}));
export const PERKS:ActivePerk[]=[...["DATA READER","MACRO READER","CROSS-ASSET ANALYST","MASTER RESEARCHER"].map((n,i)=>({id:`analysis-${i+1}`,name:n,path:"ANALYSIS" as const,tier:i+1,description:"Adds research presentation depth.",effect:"RESEARCH_DETAIL" as const,unlockLevel:i*2+1,requires:i?`analysis-${i}`:undefined})),...["LIQUIDITY DISCIPLINE","DRAWDOWN CONTROL","CRISIS MANAGEMENT","CAPITAL GUARDIAN"].map((n,i)=>({id:`risk-${i+1}`,name:n,path:"RISK" as const,tier:i+1,description:"Adds risk explanation depth.",effect:(i>1?"EXTRA_SCENARIO":"ALERT_DETAIL") as never,unlockLevel:i*2+1,requires:i?`risk-${i}`:undefined})),...["MOMENTUM AWARENESS","CONTRARIAN THINKING","SECTOR SPECIALIST","MARKET OPERATOR"].map((n,i)=>({id:`opportunity-${i+1}`,name:n,path:"OPPORTUNITY" as const,tier:i+1,description:"Adds opportunity context.",effect:"EXTRA_CONTEXT" as const,unlockLevel:i*2+1,requires:i?`opportunity-${i}`:undefined}))];
export const MENTORS:MentorDefinition[]=["INDUSTRIAL TITAN","VALUE MASTER","CREDIT ARCHITECT","MACRO VETERAN","COMMODITY LEGEND","RISK DISCIPLINARIAN","MARKET HISTORIAN"].map((name,i)=>({id:`mentor-${i+1}`,name:`THE ${name}`,inspirationType:"Historically inspired archetype",era:["Industrial Age","Great Crash","Banking Era","Oil Shock","Commodity Cycles","Modern Risk","Five Eras"][i],specialization:["INDUSTRY","STRATEGY","CREDIT","MACRO","COMMODITY","RISK","HISTORY"][i],description:"A fictional mentor informed by period financial practice.",ability:ability(`mentor-ability-${i+1}`,`${name} GUIDANCE`,"RESEARCH","EXTRA_CONTEXT","Adds one known-data context item.","Only one mentor may be active"),unlockRequirement:i===0?"Complete Industrial Age":i===1?"Complete Great Crash":i===3?"Complete Oil Shock":"Complete 5 eras"}));
