import{ARCHETYPES,AVATARS}from"./catalog";import type{InvestorLegacy,InvestorProfile}from"./models";import type{AvatarAssetManifest,AvatarPresentation,CareerBadgeDefinition,DisplayContext,EraIdentityDefinition,EraIdentityState,EraPortraitMemory,EraStyleId,LegacyPortraitConfig,PortraitMood}from"./evolution-models";
const moods:PortraitMood[]=["NEUTRAL","CALM","FOCUSED","CONCERNED","ALERT","CONFIDENT"];
export const ERA_IDENTITIES:EraIdentityDefinition[]=[
["ERA_STYLE_1900",["E01","E02","E03"],"Industrial Office","1900–1918","paper-brass","1900","dark wool suit","industrial office, dark wood and ledgers","warm low-key","BRASS_LEDGER",["paper ledger","brass desk lamp"]],
["ERA_STYLE_1920",["E04","E05","E06"],"Art Deco Wall Street","1919–1938","art-deco","1920","tailored financial attire","charcoal Wall Street office","muted gold","DECO_LINES",["ticker tape","newspaper"]],
["ERA_STYLE_1940",["E07"],"Wartime Finance","1939–1949","wartime-office","1940","restrained formal clothing","maps and paper reports","muted neutral","REPORT_FRAME",["maps","reports"]],
["ERA_STYLE_MID_CENTURY",["E08","E09"],"Mid-Century Executive","1950–1969","mid-century","mid-century","executive tailoring","clean office and printed reports","restrained optimistic","CLEAN_EXECUTIVE",["printed reports"]],
["ERA_STYLE_1970",["E10","E11"],"Commodity Press Desk","1970–1979","financial-press","1970","period tailoring","analog commodity desk","warm print","PRESS_FRAME",["commodity board","desk telephone"]],
["ERA_STYLE_1980",["E12"],"Institutional Trading Floor","1980–1989","terminal-grid","1980","strong suit silhouette","trading floor with CRT screens","high contrast","TERMINAL_FRAME",["CRT","phone desk"]],
["ERA_STYLE_1990",["E13"],"Global Electronic Markets","1990–1999","electronic-market","1990","business attire","desktop terminals","cool neutral","GLOBAL_FRAME",["terminal","world map"]],
["ERA_STYLE_2000",["E14","E15","E16"],"Digital Institution","2000–2009","multi-monitor","2000","modernizing tailoring","institutional multi-monitor desk","screen cool","DIGITAL_FRAME",["early web","multiple displays"]],
["ERA_STYLE_2010",["E17"],"Modern Asset Management","2010–2019","asset-management","2010","modern tailoring","clean global macro office","balanced clean","INSTITUTIONAL_FRAME",["laptop","institutional display"]],
["ERA_STYLE_MODERN",["E18"],"Modern Macro Desk","2020+","modern-quant","modern","contemporary tailoring","dark institutional data wall","clean directional","MODERN_FRAME",["data wall"]]
].map(x=>({id:x[0] as EraStyleId,eraId:x[1] as string[],label:x[2] as string,yearRange:x[3] as string,visualThemeId:x[4] as string,portraitVariantKey:x[5] as string,outfitStyle:x[6] as string,backgroundStyle:x[7] as string,lightingStyle:x[8] as string,frameStyle:x[9] as string,props:x[10] as string[],availableMoodVariants:moods,specialTreatments:["CRISIS_CONTRAST"]}));
export const BADGES:CareerBadgeDefinition[]=[...["PANIC SURVIVOR","CRASH SURVIVOR","WAR MARKET VETERAN","INFLATION VETERAN","DOTCOM SURVIVOR","CREDIT CRISIS VETERAN","PANDEMIC TRADER"].map((name,i)=>({id:name.toLowerCase().replaceAll(" ","-"),name,description:`Completed era ${["E02","E05","E07","E10","E14","E16","E18"][i]}.`,category:"CRISIS" as const,unlockRequirement:`Complete ${["E02","E05","E07","E10","E14","E16","E18"][i]}`,displayPriority:100-i})),{id:"century-investor",name:"CENTURY INVESTOR",description:"Reached the final era.",category:"LEGACY",unlockRequirement:"Complete 18 eras",displayPriority:120}];
export const defaultEraIdentityState=():EraIdentityState=>({unlockedVisuals:[{id:"era-style-1900",type:"ERA_VARIANT",assetReference:"ERA_STYLE_1900",requirement:"Start a career",unlockedAt:new Date().toISOString()}],eraPortraitMemories:[],careerBadges:[],settings:{autoEraLook:true,showCharacterReactions:true,showCareerBadges:true,crisisPortraitEffects:true,eraTransitionAnimation:true}});
export function styleForEra(eraId:string){return ERA_IDENTITIES.find(x=>x.eraId.includes(eraId))??ERA_IDENTITIES[0]}
export function assetManifest(avatarId:string):AvatarAssetManifest{const avatar=AVATARS.find(x=>x.id===avatarId)??AVATARS[0];return{avatarId,base:avatar.portraitAsset,eraVariants:{},moodVariants:{},fallback:avatar.portraitAsset,thumbnail:avatar.portraitAsset,status:"PLACEHOLDER",visualIdentityKey:`identity-${avatarId}`}}
export function resolveMood(input:{marketHeat?:string;crisisState?:boolean;portfolioChange?:number;riskSeverity?:string;achievement?:boolean;eraCompletion?:boolean}):PortraitMood{if(input.crisisState||input.riskSeverity==="SYSTEMIC"||input.marketHeat==="PANIC")return"ALERT";if(input.riskSeverity==="CRITICAL"||input.portfolioChange!==undefined&&input.portfolioChange<=-5)return"CONCERNED";if(input.eraCompletion||input.achievement)return"CONFIDENT";if(input.marketHeat==="CALM")return"FOCUSED";return"NEUTRAL"}
export function resolveAvatarPresentation(input:{avatarId:string;currentEraId:string;archetypeId:string;mood?:PortraitMood;crisisState?:boolean;careerBadges?:string[];displayContext:DisplayContext;visualState?:EraIdentityState}):AvatarPresentation{const manifest=assetManifest(input.avatarId),auto=input.visualState?.settings.autoEraLook!==false,manual=input.visualState?.settings.manualEraStyle,style=auto||!manual?styleForEra(input.currentEraId):ERA_IDENTITIES.find(x=>x.id===manual)??styleForEra(input.currentEraId),asset=manifest.eraVariants[style.id],badges=(input.visualState?.settings.showCareerBadges===false?[]:input.careerBadges??[]).slice(0,3),crisis=Boolean(input.crisisState&&input.visualState?.settings.crisisPortraitEffects!==false),accent=ARCHETYPES.find(x=>x.id===input.archetypeId)?.preferredAgent??"MARKET";return{portraitAsset:asset,fallbackAsset:manifest.fallback,eraStyleId:style.id,frameVariant:input.displayContext==="LEGACY"?"LEGACY":input.visualState?.settings.selectedFrame??style.frameStyle,backgroundVariant:input.visualState?.settings.selectedCosmeticBackground??style.visualThemeId,archetypeAccent:accent,mood:input.mood??"NEUTRAL",crisisTreatment:crisis?"CRISIS_CONTRAST":"NONE",badges,altText:`Investor avatar in ${style.label} (${style.yearRange}) style, ${input.mood??"NEUTRAL"} mood.`,presentationLabel:`${style.label} · ${style.yearRange}`,displayContext:input.displayContext}}
export function completeEraVisual(state:EraIdentityState,input:{profile:InvestorProfile;eraId:string;completionDate:string;grade:string;score:number;endCapital:number;legacyTitle?:string}){const style=styleForEra(input.eraId),badge=BADGES.find(x=>x.unlockRequirement.endsWith(input.eraId)),careerBadges=[...new Set([...state.careerBadges,...(badge?[badge.id]:[])])],presentation=resolveAvatarPresentation({avatarId:input.profile.avatarId,currentEraId:input.eraId,archetypeId:input.profile.archetypeId,mood:"CONFIDENT",careerBadges,displayContext:"ERA_COMPLETE",visualState:state}),memory:EraPortraitMemory={eraId:input.eraId,portraitPresentation:presentation,completionDate:input.completionDate,grade:input.grade,score:input.score,endCapital:input.endCapital,legacyTitleAtTime:input.legacyTitle,badgesEarned:badge?[badge.id]:[]};return{...state,careerBadges,unlockedVisuals:[...state.unlockedVisuals,{id:`era-style-${style.id}`,type:"ERA_VARIANT" as const,assetReference:style.id,requirement:`Reach ${input.eraId}`,unlockedAt:input.completionDate},...(badge?[{id:`badge-${badge.id}`,type:"BADGE" as const,assetReference:badge.id,requirement:badge.unlockRequirement,unlockedAt:input.completionDate}]:[])].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i),eraPortraitMemories:[...state.eraPortraitMemories.filter(x=>x.eraId!==input.eraId),memory]}}
export function legacyPortrait(profile:InvestorProfile,legacy:InvestorLegacy,state:EraIdentityState):LegacyPortraitConfig{const frameTier=legacy.legacyScore>=850?"LEGEND":legacy.legacyScore>=650?"MASTER":legacy.legacyScore>=400?"VETERAN":"CLASSIC";return{presentation:resolveAvatarPresentation({avatarId:profile.avatarId,currentEraId:"E18",archetypeId:profile.archetypeId,mood:"CONFIDENT",careerBadges:state.careerBadges,displayContext:"LEGACY",visualState:state}),frameTier,signatureStyle:legacy.signatureStyle,legacyTitle:legacy.legacyTitle}}
