export type EraStyleId="ERA_STYLE_1900"|"ERA_STYLE_1920"|"ERA_STYLE_1940"|"ERA_STYLE_MID_CENTURY"|"ERA_STYLE_1970"|"ERA_STYLE_1980"|"ERA_STYLE_1990"|"ERA_STYLE_2000"|"ERA_STYLE_2010"|"ERA_STYLE_MODERN";export type PortraitMood="NEUTRAL"|"CALM"|"FOCUSED"|"CONCERNED"|"ALERT"|"CONFIDENT"|"EXHAUSTED";export type DisplayContext="PROFILE"|"HEADER"|"EVENT_REACTION"|"ERA_INTRO"|"ERA_COMPLETE"|"LEGACY"|"CHARACTER_SELECT"|"ANALYST_DESK";export type BadgeCategory="CRISIS"|"ERA"|"RESEARCH"|"RISK"|"STRATEGY"|"MARKET"|"LEGACY";
export interface EraIdentityDefinition{id:EraStyleId;eraId:string[];label:string;yearRange:string;visualThemeId:string;portraitVariantKey:string;outfitStyle:string;backgroundStyle:string;lightingStyle:string;frameStyle:string;props:string[];availableMoodVariants:PortraitMood[];specialTreatments:string[]}
export interface AvatarEraVariant{id:string;avatarId:string;eraIdentityId:EraStyleId;portraitAsset?:string;fallbackAsset:string;cropConfig:{x:number;y:number;scale:number};visualMetadata:{status:"PLACEHOLDER"|"GENERATED"|"APPROVED"|"FINAL";visualIdentityKey:string};unlockState:"STARTER"|"UNLOCKED"|"LOCKED"}
export interface AvatarPresentation{portraitAsset?:string;fallbackAsset:string;eraStyleId:EraStyleId;frameVariant:string;backgroundVariant:string;archetypeAccent:string;mood:PortraitMood;crisisTreatment:"NONE"|"CRISIS_CONTRAST";badges:string[];altText:string;presentationLabel:string;displayContext:DisplayContext}
export interface AvatarAssetManifest{avatarId:string;base:string;eraVariants:Partial<Record<EraStyleId,string>>;moodVariants:Partial<Record<PortraitMood,string>>;fallback:string;thumbnail:string;status:"PLACEHOLDER"|"GENERATED"|"APPROVED"|"FINAL";visualIdentityKey:string}
export interface CareerBadgeDefinition{id:string;name:string;description:string;category:BadgeCategory;unlockRequirement:string;displayPriority:number;iconAsset?:string}
export interface EraPortraitMemory{eraId:string;portraitPresentation:AvatarPresentation;completionDate:string;grade:string;score:number;endCapital:number;legacyTitleAtTime?:string;badgesEarned:string[]}
export interface VisualUnlock{id:string;type:"ERA_VARIANT"|"FRAME"|"BACKGROUND"|"BADGE"|"OUTFIT"|"LEGACY_STYLE";assetReference:string;requirement:string;unlockedAt:string}
export interface LegacyPortraitConfig{presentation:AvatarPresentation;frameTier:"CLASSIC"|"VETERAN"|"MASTER"|"LEGEND";signatureStyle:string;legacyTitle:string}
export interface CharacterVisualSettings{autoEraLook:boolean;showCharacterReactions:boolean;showCareerBadges:boolean;crisisPortraitEffects:boolean;eraTransitionAnimation:boolean;manualEraStyle?:EraStyleId;selectedFrame?:string;selectedCosmeticBackground?:string}
export interface EraIdentityState{unlockedVisuals:VisualUnlock[];eraPortraitMemories:EraPortraitMemory[];careerBadges:string[];legacyPortraitConfig?:LegacyPortraitConfig;settings:CharacterVisualSettings}
