import{describe,expect,it}from"vitest";import{createAppSave,migrateToV3,newCareerSave}from"../campaign/persistence";import{configureProfile}from"./service";import{BADGES,ERA_IDENTITIES,completeEraVisual,defaultEraIdentityState,legacyPortrait,resolveAvatarPresentation,resolveMood}from"./evolution";import type{InvestorLegacy}from"./models";
const profile=()=>configureProfile(newCareerSave().investorProfile!,{displayName:"Martin",avatarId:"female-macro-01",archetypeId:"MACRO_STRATEGIST",genderPresentation:"FEMALE",startingStrategy:"DEFENSIVE"});
describe("Sprint 4.6 era identity",()=>{
it("covers all ten requested era style groups",()=>expect(ERA_IDENTITIES.map(x=>x.id)).toEqual(["ERA_STYLE_1900","ERA_STYLE_1920","ERA_STYLE_1940","ERA_STYLE_MID_CENTURY","ERA_STYLE_1970","ERA_STYLE_1980","ERA_STYLE_1990","ERA_STYLE_2000","ERA_STYLE_2010","ERA_STYLE_MODERN"]));
it("keeps the same identity across eras",()=>{const p=profile(),a=resolveAvatarPresentation({avatarId:p.avatarId,currentEraId:"E01",archetypeId:p.archetypeId,displayContext:"PROFILE"}),b=resolveAvatarPresentation({avatarId:p.avatarId,currentEraId:"E12",archetypeId:p.archetypeId,displayContext:"PROFILE"});expect(a.fallbackAsset).toBe(b.fallbackAsset);expect(a.eraStyleId).not.toBe(b.eraStyleId);expect(p).toMatchObject({displayName:"Martin",genderPresentation:"FEMALE",archetypeId:"MACRO_STRATEGIST"})});
it("prioritizes systemic crisis mood over gains",()=>expect(resolveMood({crisisState:true,portfolioChange:10,achievement:true})).toBe("ALERT"));
it("uses confident completion and focused calm moods",()=>{expect(resolveMood({eraCompletion:true})).toBe("CONFIDENT");expect(resolveMood({marketHeat:"CALM"})).toBe("FOCUSED")});
it("always returns a valid fallback without a specific era asset",()=>{const x=resolveAvatarPresentation({avatarId:"female-macro-01",currentEraId:"E10",archetypeId:"MACRO_STRATEGIST",displayContext:"PROFILE"});expect(x.portraitAsset).toBeUndefined();expect(x.fallbackAsset).toMatch(/\.webp$/);expect(x.altText).toContain("1970")});
it("unlocks a crash badge and displays at most three",()=>{const p=profile(),base={...defaultEraIdentityState(),careerBadges:["one","two","three","four"]},x=completeEraVisual(base,{profile:p,eraId:"E05",completionDate:"1933-12-31",grade:"A",score:800,endCapital:120000});expect(x.careerBadges).toContain("crash-survivor");const shown=resolveAvatarPresentation({avatarId:p.avatarId,currentEraId:"E05",archetypeId:p.archetypeId,careerBadges:x.careerBadges,displayContext:"PROFILE",visualState:x});expect(shown.badges).toHaveLength(3);expect(BADGES.some(b=>b.id==="crash-survivor")).toBe(true)});
it("stores only completed portrait memories as frozen snapshots",()=>{const p=profile(),x=completeEraVisual(defaultEraIdentityState(),{profile:p,eraId:"E05",completionDate:"1933-12-31",grade:"B",score:650,endCapital:90000}),snapshot=JSON.stringify(x.eraPortraitMemories[0]);resolveAvatarPresentation({avatarId:p.avatarId,currentEraId:"E05",archetypeId:p.archetypeId,mood:"ALERT",crisisState:true,displayContext:"EVENT_REACTION",visualState:x});expect(x.eraPortraitMemories).toHaveLength(1);expect(JSON.stringify(x.eraPortraitMemories[0])).toBe(snapshot)});
it("manual mode accepts only the persisted unlocked selection",()=>{const state=defaultEraIdentityState();state.settings.autoEraLook=false;state.settings.manualEraStyle="ERA_STYLE_1900";const x=resolveAvatarPresentation({avatarId:profile().avatarId,currentEraId:"E12",archetypeId:"MACRO_STRATEGIST",displayContext:"PROFILE",visualState:state});expect(x.eraStyleId).toBe("ERA_STYLE_1900")});
it("creates a deterministic legacy portrait",()=>{const p=profile(),state=defaultEraIdentityState(),legacy={careerId:p.careerId,investorName:p.displayName,archetype:p.archetypeId,careerStart:"1900",careerEnd:"2026",erasCompleted:18,crisesSurvived:7,finalCapital:500000,careerReturn:400,maxDrawdown:12,bestEra:"E18",worstEra:"E05",benchmarkWins:10,strategyViolations:1,researchUsage:20,agentUsage:30,topAssetClass:"EQUITY",signatureStyle:"DEFENSIVE MACRO",legacyScore:900,legacyTitle:"THE CAPITAL GUARDIAN"} satisfies InvestorLegacy;expect(legacyPortrait(p,legacy,state)).toEqual(legacyPortrait(p,legacy,state));expect(legacyPortrait(p,legacy,state).frameTier).toBe("LEGEND")});
it("migrates a Sprint 4.5 save with identity intact",()=>{const old=createAppSave(),p=profile(),raw={...old,investorProfile:p}as unknown as Record<string,unknown>;delete raw.eraIdentityState;const x=migrateToV3(raw);expect(x.investorProfile).toEqual(p);expect(x.eraIdentityState.settings.autoEraLook).toBe(true);expect(x.eraIdentityState.eraPortraitMemories).toEqual([])});
});
