import{describe,expect,it}from"vitest";import{runAgentRuntime}from"../agents/runtime";import{createAppSave,migrateToV3,newCareerSave}from"../campaign/persistence";import{createNewGame,startGame}from"../engine/game-engine";import{ARCHETYPES,AVATARS,MENTORS,PERKS}from"./catalog";import{activateMentor,configureProfile,deriveLegacy,eraTrait,personalizeAnalyses,presentationFor,reactionFor,setActivePerks,setActiveTraits,unlockTrait}from"./service";
const configured=(archetypeId="VALUE_INVESTOR",genderPresentation:"MALE"|"FEMALE"="MALE")=>{const save=newCareerSave(),p=save.investorProfile!;return configureProfile(p,{displayName:"Martin",avatarId:genderPresentation==="MALE"?"male-industrialist-01":"female-industrialist-01",archetypeId,genderPresentation,startingStrategy:"BALANCED"})};
describe("Sprint 4.5 investor identity",()=>{
it("provides twelve varied starter avatars without gameplay fields",()=>{expect(AVATARS.filter(x=>x.isStarter&&x.genderPresentation==="MALE")).toHaveLength(6);expect(AVATARS.filter(x=>x.isStarter&&x.genderPresentation==="FEMALE")).toHaveLength(6);expect(AVATARS.every(x=>!("priceMultiplier"in x))).toBe(true)});
it("defines ten balanced archetypes and allowed abilities",()=>{expect(ARCHETYPES).toHaveLength(10);expect(ARCHETYPES.every(x=>x.coreAbility.tradeoffs.length===1)).toBe(true);expect(ARCHETYPES.every(x=>!["PRICE_MULTIPLIER","RETURN_BOOST","RANDOM_PROFIT"].includes(x.coreAbility.effectType))).toBe(true)});
it("persists a complete character selection",()=>{const p=configured("MACRO_STRATEGIST");expect(p).toMatchObject({displayName:"Martin",archetypeId:"MACRO_STRATEGIST",startingStrategy:"BALANCED",needsCharacterSetup:false})});
it("gender presentation has no mathematical effect",()=>{const male=presentationFor(configured("RISK_OFFICER","MALE")),female=presentationFor(configured("RISK_OFFICER","FEMALE"));expect(male).toEqual(female)});
it("caps active traits at three",()=>{let p=configured();for(let i=0;i<4;i++)p=unlockTrait(p,{id:`t${i}`,name:`T${i}`,description:"",category:"RISK",source:"CAREER_LEVEL",unlockedAt:"1929-01-01",effects:["EXTRA_CONTEXT"]});expect(()=>setActiveTraits(p,["t0","t1","t2","t3"])).toThrow();expect(setActiveTraits(p,["t0","t1","t2"]).activeTraitIds).toHaveLength(3)});
it("enforces perk progression and three slots",()=>{const p={...configured(),unlockedPerks:PERKS.map(x=>x.id)};expect(()=>setActivePerks(p,["analysis-2"])).not.toThrow();expect(()=>setActivePerks(p,["analysis-1","risk-1","opportunity-1","analysis-2"])).toThrow()});
it("allows only unlocked mentors and one active mentor",()=>{const p={...configured(),mentorIds:[MENTORS[0].id,MENTORS[1].id]};expect(activateMentor(activateMentor(p,MENTORS[0].id),MENTORS[1].id).activeMentorId).toBe(MENTORS[1].id);expect(()=>activateMentor(p,MENTORS[2].id)).toThrow()});
it("personalization preserves objective agent signals and market prices",()=>{const game=startGame(createNewGame()),base=runAgentRuntime(game).analyses,prices={...game.marketState.prices},shown=personalizeAnalyses(base,configured("MACRO_STRATEGIST"));for(const original of base)expect(shown.find(x=>x.agentId===original.agentId)?.signals).toEqual(original.signals);expect(game.marketState.prices).toEqual(prices)});
it("does not leak future history through historian presentation",()=>{const game={...startGame(createNewGame()),currentDate:"1929-09-01"},run=runAgentRuntime(game),shown=personalizeAnalyses(run.analyses,configured("MARKET_HISTORIAN"));expect(shown.some(x=>x.relatedEvents.includes("black-thursday"))).toBe(false);expect(shown.some(x=>x.summary.includes("Black Thursday"))).toBe(false)});
it("emits at most one relevant reaction",()=>{const summary={...startGame(createNewGame()).lastBriefing!,newEvents:[],newNews:[],newRiskAlerts:[],roundNumber:1,date:"1929-01-01",portfolioValue:90000,weeklyChange:-6,cash:50000,cashChange:0,sentiment:"PANIC" as const,strategyViolationCount:0};expect([reactionFor(configured("INDUSTRIALIST"),summary,true)].filter(Boolean)).toHaveLength(1)});
it("derives deterministic legacy from behavior rather than chosen label",()=>{const save=newCareerSave(),p=configured("SPECULATOR"),career={...save.career!,capital:120000},game={...startGame(createNewGame()),cash:90000,portfolioValue:100000,maxDrawdown:5},a=deriveLegacy(career,p,save.stats,[game]),b=deriveLegacy(career,p,save.stats,[game]);expect(a).toEqual(b);expect(a.signatureStyle).toBe("CAPITAL PRESERVER")});
it("migrates existing careers into required setup without data loss",()=>{const old=createAppSave(),career=newCareerSave().career!;const raw={...old,career}as unknown as Record<string,unknown>;delete raw.investorProfile;delete raw.characterHistory;const migrated=migrateToV3(raw);expect(migrated.investorProfile?.needsCharacterSetup).toBe(true);expect(migrated.career?.capital).toBe(career.capital)});
it("unlocks deterministic era traits",()=>{expect(eraTrait("great-crash","1933-01-01")?.name).toBe("CRASH SURVIVOR")});
});
