import type{AgentId}from"../agents/models";
import type{StrategyTemplate}from"../types";
export type GenderPresentation="MALE"|"FEMALE"|"UNSPECIFIED";export type AbilityCategory="INFORMATION"|"RESEARCH"|"RISK"|"STRATEGY"|"MARKET"|"MACRO"|"COMMODITY"|"CRISIS"|"HISTORY";export type EffectType="PRIORITY_BOOST"|"EXTRA_CONTEXT"|"EXTRA_SCENARIO"|"LOWER_NOISE"|"RESEARCH_DETAIL"|"WATCHLIST_CAPACITY"|"ALERT_DETAIL"|"STRATEGY_EXPLANATION";
export interface AbilityDefinition{id:string;name:string;description:string;category:AbilityCategory;effectType:EffectType;effectConfig:Record<string,number|string>;conditions:string[];tradeoffs:string[];unlockRequirement?:string}
export interface AvatarDefinition{id:string;name:string;genderPresentation:GenderPresentation;portraitAsset:string;eraStyle:string;visualTags:string[];unlockRequirement?:string;isStarter:boolean}
export interface ArchetypeDefinition{id:string;name:string;focus:string[];coreAbility:AbilityDefinition;secondaryStrength:string;tradeoff:string;preferredAgent:AgentId}
export type TraitSource="ARCHETYPE"|"ERA_COMPLETION"|"ACHIEVEMENT"|"CRISIS"|"CAREER_LEVEL"|"MENTOR"|"SPECIAL_CHALLENGE";export interface InvestorTrait{id:string;name:string;description:string;category:AbilityCategory;source:TraitSource;unlockedAt:string;effects:EffectType[]}
export type PerkPath="ANALYSIS"|"RISK"|"OPPORTUNITY";export interface ActivePerk{id:string;name:string;path:PerkPath;tier:number;description:string;effect:EffectType;unlockLevel:number;requires?:string}
export interface MentorDefinition{id:string;name:string;inspirationType:string;era:string;specialization:string;description:string;ability:AbilityDefinition;unlockRequirement:string;portraitStyle?:string}
export interface CharacterReaction{id:string;archetypeId:string;triggerType:"NEW_ERA"|"CRISIS_START"|"SYSTEMIC_EVENT"|"LARGE_GAIN"|"LARGE_LOSS"|"STRATEGY_VIOLATION"|"ACHIEVEMENT"|"ERA_COMPLETE";triggerCondition:string;textVariants:string[];severity:"INFO"|"ELEVATED"|"CRITICAL"}
export interface LegacyStats{erasCompleted:number;crisesSurvived:number;benchmarkWins:number;strategyViolations:number;researchUsage:number;agentUsage:number}
export interface CharacterHistory{selectedArchetypes:{id:string;date:string}[];perkUnlocks:string[];traitUnlocks:string[];mentorUnlocks:string[];mentorChanges:{id:string;date:string}[];perkChanges:{ids:string[];date:string}[];avatarChanges:{id:string;date:string}[]}
export interface InvestorProfile{id:string;careerId:string;displayName:string;avatarId:string;archetypeId:string;genderPresentation:GenderPresentation;background:string;bio:string;createdAt:string;level:number;xp:number;traits:InvestorTrait[];activeTraitIds:string[];unlockedPerks:string[];activePerks:string[];mentorIds:string[];activeMentorId?:string;startingStrategy:StrategyTemplate;legacyStats:LegacyStats;needsCharacterSetup:boolean}
export interface InvestorLegacy{careerId:string;investorName:string;archetype:string;careerStart:string;careerEnd:string;erasCompleted:number;crisesSurvived:number;finalCapital:number;careerReturn:number;maxDrawdown:number;bestEra:string;worstEra:string;benchmarkWins:number;strategyViolations:number;researchUsage:number;agentUsage:number;topAssetClass:string;signatureStyle:string;legacyScore:number;legacyTitle:string}
