import type{AgentAnalysis}from"../agents/models";import type{CareerState,CareerStats}from"../campaign/types";import type{GameState,RoundSummary,StrategyTemplate}from"../types";import{ARCHETYPES,MENTORS,PERKS}from"./catalog";import type{CharacterHistory,CharacterReaction,GenderPresentation,InvestorLegacy,InvestorProfile,InvestorTrait}from"./models";
export const MAX_ACTIVE_TRAITS=3,MAX_ACTIVE_PERKS=3;
export function defaultHistory():CharacterHistory{return{selectedArchetypes:[],perkUnlocks:[],traitUnlocks:[],mentorUnlocks:[],mentorChanges:[],perkChanges:[],avatarChanges:[]}}
export function createPendingProfile(career:CareerState):InvestorProfile{return{id:`investor-${career.id}`,careerId:career.id,displayName:"Investor",avatarId:"male-industrialist-01",archetypeId:"VALUE_INVESTOR",genderPresentation:"UNSPECIFIED",background:"Independent investor",bio:"A career shaped by decisions across market history.",createdAt:career.createdAt,level:career.level,xp:career.xp,traits:[],activeTraitIds:[],unlockedPerks:["analysis-1","risk-1","opportunity-1"],activePerks:[],mentorIds:[],startingStrategy:"BALANCED",legacyStats:{erasCompleted:career.completedEpisodeIds.length,crisesSurvived:0,benchmarkWins:0,strategyViolations:0,researchUsage:0,agentUsage:0},needsCharacterSetup:true}}
export function configureProfile(base:InvestorProfile,input:{displayName:string;avatarId:string;archetypeId:string;genderPresentation:GenderPresentation;startingStrategy:StrategyTemplate}):InvestorProfile{return{...base,...input,displayName:input.displayName.trim()||"Investor",needsCharacterSetup:false}}
export function setActiveTraits(p:InvestorProfile,ids:string[]){const valid=ids.filter(id=>p.traits.some(t=>t.id===id));if(valid.length>MAX_ACTIVE_TRAITS)throw new Error("Maximum three active traits");return{...p,activeTraitIds:[...new Set(valid)]}}
export function unlockTrait(p:InvestorProfile,trait:InvestorTrait){return p.traits.some(x=>x.id===trait.id)?p:{...p,traits:[...p.traits,trait]}}
export function progressProfile(p:InvestorProfile,career:CareerState,episodeId:string,date:string){const reward=eraTrait(episodeId,date),withTrait=reward?unlockTrait(p,reward):p,unlockedPerks=PERKS.filter(x=>x.unlockLevel<=career.level).map(x=>x.id),mentorIds=[...withTrait.mentorIds];if(episodeId==="panic-1907")mentorIds.push("mentor-1");if(episodeId==="great-crash")mentorIds.push("mentor-2");if(episodeId==="oil-shock")mentorIds.push("mentor-4");if(career.completedEpisodeIds.length>=5)mentorIds.push("mentor-7");return{...withTrait,level:career.level,xp:career.xp,unlockedPerks:[...new Set([...withTrait.unlockedPerks,...unlockedPerks])],mentorIds:[...new Set(mentorIds)],legacyStats:{...withTrait.legacyStats,erasCompleted:career.completedEpisodeIds.length}}}
export function setActivePerks(p:InvestorProfile,ids:string[]){const unique=[...new Set(ids)];if(unique.length>MAX_ACTIVE_PERKS)throw new Error("Maximum three active perks");for(const id of unique){const perk=PERKS.find(x=>x.id===id);if(!perk||!p.unlockedPerks.includes(id)||perk.requires&&!p.unlockedPerks.includes(perk.requires))throw new Error("Perk is locked")};return{...p,activePerks:unique}}
export function activateMentor(p:InvestorProfile,id:string){if(!p.mentorIds.includes(id)||!MENTORS.some(x=>x.id===id))throw new Error("Mentor is locked");return{...p,activeMentorId:id}}
export function presentationFor(p:InvestorProfile|undefined){const archetype=ARCHETYPES.find(x=>x.id===p?.archetypeId);return{preferredAgent:archetype?.preferredAgent,detailBoost:archetype?.coreAbility.effectType==="EXTRA_CONTEXT"||archetype?.coreAbility.effectType==="RESEARCH_DETAIL",scenarioSlots:1+(archetype?.coreAbility.effectType==="EXTRA_SCENARIO"?1:0)+((p?.activePerks??[]).some(x=>PERKS.find(y=>y.id===x)?.effect==="EXTRA_SCENARIO")?1:0),watchlistCapacity:10+(p?.activePerks.includes("analysis-1")?2:0)}}
export function personalizeAnalyses(a:AgentAnalysis[],p?:InvestorProfile){const pref=presentationFor(p);return[...a].sort((x,y)=>Number(y.agentId===pref.preferredAgent)-Number(x.agentId===pref.preferredAgent)).map(x=>({...x,summary:x.agentId===pref.preferredAgent&&pref.detailBoost?`${x.summary} Additional known-data context is prioritized for your investor profile.`:x.summary}))}
export const REACTIONS:CharacterReaction[]=[{id:"risk-crisis",archetypeId:"RISK_OFFICER",triggerType:"CRISIS_START",triggerCondition:"crisis",textVariants:["Your exposure matters more than your conviction right now."],severity:"CRITICAL"},{id:"macro-systemic",archetypeId:"MACRO_STRATEGIST",triggerType:"SYSTEMIC_EVENT",triggerCondition:"systemic",textVariants:["This is becoming more than a market story."],severity:"CRITICAL"},{id:"industrial-loss",archetypeId:"INDUSTRIALIST",triggerType:"LARGE_LOSS",triggerCondition:"loss<-5",textVariants:["Industry is weakening beneath the headline numbers."],severity:"ELEVATED"}];
export function reactionFor(p:InvestorProfile|undefined,summary:RoundSummary,isCrisis:boolean){if(!p)return undefined;const trigger=summary.newEvents.some(x=>x.severity==="SYSTEMIC")?"SYSTEMIC_EVENT":isCrisis?"CRISIS_START":summary.weeklyChange<=-5?"LARGE_LOSS":summary.weeklyChange>=5?"LARGE_GAIN":summary.strategyViolationCount?"STRATEGY_VIOLATION":undefined;const exact=REACTIONS.find(x=>x.archetypeId===p.archetypeId&&x.triggerType===trigger);if(exact)return{...exact,text:exact.textVariants[0]};if(!trigger)return undefined;const archetype=ARCHETYPES.find(x=>x.id===p.archetypeId);return{id:`${p.archetypeId}-${trigger}-${summary.roundNumber}`,archetypeId:p.archetypeId,triggerType:trigger,triggerCondition:"important round",textVariants:[`${archetype?.name??"Your investor"}: review the known evidence before acting.`],severity:isCrisis?"CRITICAL":"ELEVATED",text:`${archetype?.name??"Your investor"}: review the known evidence before acting.`}}
export function eraTrait(episodeId:string,date:string):InvestorTrait|undefined{const map:Record<string,[string,string,InvestorTrait["category"]]>={"panic-1907":["PANIC VETERAN","Credit and liquidity alerts receive additional context.","RISK"],"great-crash":["CRASH SURVIVOR","Crisis briefings include known historical comparisons.","HISTORY"],"oil-shock":["INFLATION VETERAN","Inflation and commodity context is expanded.","COMMODITY"]};const x=map[episodeId];return x?{id:x[0].toLowerCase().replaceAll(" ","-"),name:x[0],description:x[1],category:x[2],source:"ERA_COMPLETION",unlockedAt:date,effects:["EXTRA_CONTEXT"]}:undefined}
export function deriveLegacy(career:CareerState,profile:InvestorProfile,stats:CareerStats,games:GameState[]):InvestorLegacy{const trades=games.reduce((n,g)=>n+g.tradeHistory.length,0),drawdown=Math.max(0,...games.map(g=>g.maxDrawdown)),last=games.at(-1),cash=last?last.cash/(last.portfolioValue||1)*100:100,style=cash>50&&drawdown<15?"CAPITAL PRESERVER":trades>40?"AGGRESSIVE MOMENTUM":profile.archetypeId==="MACRO_STRATEGIST"?"DEFENSIVE MACRO":profile.archetypeId==="COMMODITY_TRADER"?"COMMODITY SPECIALIST":"BALANCED VALUE",score=Math.min(1000,career.completedEpisodeIds.length*35+Math.max(0,250-drawdown*5)+Math.min(150,profile.legacyStats.researchUsage*5)+Math.min(150,stats.bestScore*.15)),title=career.completedEpisodeIds.length>=18?"THE CENTURY INVESTOR":style==="CAPITAL PRESERVER"?"THE CAPITAL GUARDIAN":drawdown<10?"THE RISK MASTER":trades>40?"THE MARKET OPERATOR":"THE SURVIVOR";return{careerId:career.id,investorName:profile.displayName,archetype:profile.archetypeId,careerStart:career.createdAt,careerEnd:career.updatedAt,erasCompleted:career.completedEpisodeIds.length,crisesSurvived:profile.legacyStats.crisesSurvived,finalCapital:career.capital,careerReturn:(career.capital/100000-1)*100,maxDrawdown:drawdown,bestEra:career.eraProgress.reduce((a,b)=>(b.bestScore??0)>(a.bestScore??0)?b:a).eraId,worstEra:career.eraProgress.filter(x=>x.bestScore!==undefined).sort((a,b)=>(a.bestScore??0)-(b.bestScore??0))[0]?.eraId??"N/A",benchmarkWins:profile.legacyStats.benchmarkWins,strategyViolations:profile.legacyStats.strategyViolations,researchUsage:profile.legacyStats.researchUsage,agentUsage:profile.legacyStats.agentUsage,topAssetClass:"EQUITY",signatureStyle:style,legacyScore:Math.round(score),legacyTitle:title}}
