import{CHARACTER_ARCHETYPES,CHARACTER_TRAITS,CHARACTER_WEAKNESSES}from"./catalog";import{CHARACTER_SKILLS}from"./skills";import{CharacterSchema}from"./schema";import{CHARACTER_STAT_KEYS,CHARACTER_STAT_MAX,CHARACTER_STAT_MIN,type Character,type CharacterArchetypeId,type CharacterModifier,type CharacterSkillDefinition,type CharacterSkillId,type CharacterStats,type CharacterTraitId,type CharacterWeaknessId,type CreditRewardReason}from"./models";
export interface CreateCharacterInput{id?:string;actorType?:Character["actorType"];name:string;avatar:string;archetype:CharacterArchetypeId;traits:[CharacterTraitId,CharacterTraitId];weakness:CharacterWeaknessId;level?:number;xp?:number}
const clamp=(n:number)=>Math.max(CHARACTER_STAT_MIN,Math.min(CHARACTER_STAT_MAX,Math.round(n)));
export function createCharacter(input:CreateCharacterInput):Character{const archetype=CHARACTER_ARCHETYPES.find(x=>x.id===input.archetype);if(!archetype)throw new Error("Unknown archetype");return CharacterSchema.parse({schemaVersion:1,id:input.id??`character-${Date.now()}`,actorType:input.actorType??"PLAYER",name:input.name,avatar:input.avatar,archetype:input.archetype,traits:input.traits,weakness:input.weakness,stats:{...archetype.baseStats},level:input.level??1,xp:input.xp??0,reputation:archetype.baseStats.reputation,credits:0,unlockedSkills:[]})}
export function getCharacterModifiers(character:Character):CharacterModifier[]{return[...character.traits.flatMap(id=>CHARACTER_TRAITS.find(x=>x.id===id)?.modifiers??[]),...(CHARACTER_WEAKNESSES.find(x=>x.id===character.weakness)?.modifiers??[]),...character.unlockedSkills.flatMap(id=>CHARACTER_SKILLS.find(x=>x.id===id)?.modifiers??[])]}
export function getEffectiveCharacterStats(character:Character):CharacterStats{const stats={...character.stats};for(const modifier of getCharacterModifiers(character)){if(!modifier.stat)continue;stats[modifier.stat]=modifier.operation==="ADD"?stats[modifier.stat]+modifier.value:stats[modifier.stat]*modifier.value}for(const key of CHARACTER_STAT_KEYS)stats[key]=clamp(stats[key]);return stats}
export function getXpRequiredForNextLevel(level:number){return Math.max(100,level*250)}
export function addCharacterXp(character:Character,earned:number):Character{let level=character.level,xp=character.xp+Math.max(0,Math.floor(earned));while(xp>=getXpRequiredForNextLevel(level)){xp-=getXpRequiredForNextLevel(level);level++}return{...character,level,xp}}
export function awardCharacterCredits(character:Character,amount:number,reason:CreditRewardReason):Character{void reason;if(!Number.isInteger(amount)||amount<0)throw new Error("Credit award must be a non-negative integer");return{...character,credits:character.credits+amount}}
export function canSpendCharacterCredits(character:Character,amount:number){return Number.isInteger(amount)&&amount>=0&&character.credits>=amount}
export function spendCharacterCredits(character:Character,amount:number):Character{if(!canSpendCharacterCredits(character,amount))throw new Error("Insufficient credits or invalid amount");return{...character,credits:character.credits-amount}}
export type SkillUnlockReason="owned"|"insufficient_credits"|"level_required"|"missing_prerequisite"|"archetype_restricted"|"unknown_skill";
export type SkillUnlockStatus={allowed:true;skill:CharacterSkillDefinition}|{allowed:false;reason:SkillUnlockReason;skill?:CharacterSkillDefinition};
export function canUnlockCharacterSkill(character:Character,id:CharacterSkillId):SkillUnlockStatus{const skill=CHARACTER_SKILLS.find(x=>x.id===id);if(!skill)return{allowed:false,reason:"unknown_skill"};if(character.unlockedSkills.includes(id))return{allowed:false,reason:"owned",skill};if(character.credits<skill.creditCost)return{allowed:false,reason:"insufficient_credits",skill};if(character.level<(skill.requiredLevel??1))return{allowed:false,reason:"level_required",skill};if(skill.prerequisites?.some(id=>!character.unlockedSkills.includes(id)))return{allowed:false,reason:"missing_prerequisite",skill};if(skill.allowedArchetypes&&!skill.allowedArchetypes.includes(character.archetype))return{allowed:false,reason:"archetype_restricted",skill};return{allowed:true,skill}}
export function unlockCharacterSkill(character:Character,id:CharacterSkillId):Character{const status=canUnlockCharacterSkill(character,id);if(!status.allowed)throw new Error(status.reason);return CharacterSchema.parse({...spendCharacterCredits(character,status.skill.creditCost),unlockedSkills:[...character.unlockedSkills,id]})}
const legacyMap:Record<string,CharacterArchetypeId>={SPECULATOR:"SPECULATOR",VALUE_INVESTOR:"VALUE_INVESTOR",BANKER:"BANKER",CRISIS_INVESTOR:"CRISIS_TRADER",MACRO_STRATEGIST:"VALUE_INVESTOR",INDUSTRIALIST:"CORPORATE_RAIDER",COMMODITY_TRADER:"SPECULATOR",RISK_OFFICER:"BANKER"};
export function createLegacyCharacter(profile:{id:string;displayName:string;avatarId:string;archetypeId:string;level:number;xp:number}):Character{return createCharacter({id:`character-${profile.id}`,name:profile.displayName||"Investor",avatar:profile.avatarId||"male-industrialist-01",archetype:legacyMap[profile.archetypeId]??"VALUE_INVESTOR",traits:["DEEP_RESEARCH","CALCULATED_RISK"],weakness:"RISK_AVERSE",level:Math.max(1,profile.level||1),xp:Math.max(0,profile.xp||0)})}
export function upgradeCharacterProgression(character:Character):Character{return CharacterSchema.parse({...character,credits:character.credits??0,unlockedSkills:character.unlockedSkills??[]})}
