import{CHARACTER_ARCHETYPES,CHARACTER_TRAITS,CHARACTER_WEAKNESSES}from"./catalog";import{CharacterSchema}from"./schema";import{CHARACTER_STAT_KEYS,CHARACTER_STAT_MAX,CHARACTER_STAT_MIN,type Character,type CharacterArchetypeId,type CharacterStats,type CharacterTraitId,type CharacterWeaknessId}from"./models";
export interface CreateCharacterInput{id?:string;actorType?:Character["actorType"];name:string;avatar:string;archetype:CharacterArchetypeId;traits:[CharacterTraitId,CharacterTraitId];weakness:CharacterWeaknessId;level?:number;xp?:number}
const clamp=(n:number)=>Math.max(CHARACTER_STAT_MIN,Math.min(CHARACTER_STAT_MAX,Math.round(n)));
export function createCharacter(input:CreateCharacterInput):Character{const archetype=CHARACTER_ARCHETYPES.find(x=>x.id===input.archetype);if(!archetype)throw new Error("Unknown archetype");return CharacterSchema.parse({schemaVersion:1,id:input.id??`character-${Date.now()}`,actorType:input.actorType??"PLAYER",name:input.name,avatar:input.avatar,archetype:input.archetype,traits:input.traits,weakness:input.weakness,stats:{...archetype.baseStats},level:input.level??1,xp:input.xp??0,reputation:archetype.baseStats.reputation})}
export function getEffectiveCharacterStats(character:Character):CharacterStats{const stats={...character.stats};const sources=[...character.traits.map(id=>CHARACTER_TRAITS.find(x=>x.id===id)),CHARACTER_WEAKNESSES.find(x=>x.id===character.weakness)];for(const source of sources)for(const modifier of source?.modifiers??[]){if(!modifier.stat)continue;stats[modifier.stat]=modifier.operation==="ADD"?stats[modifier.stat]+modifier.value:stats[modifier.stat]*modifier.value}for(const key of CHARACTER_STAT_KEYS)stats[key]=clamp(stats[key]);return stats}
export function getXpRequiredForNextLevel(level:number){return Math.max(100,level*250)}
export function addCharacterXp(character:Character,earned:number):Character{let level=character.level,xp=character.xp+Math.max(0,Math.floor(earned));while(xp>=getXpRequiredForNextLevel(level)){xp-=getXpRequiredForNextLevel(level);level++}return{...character,level,xp}}
const legacyMap:Record<string,CharacterArchetypeId>={SPECULATOR:"SPECULATOR",VALUE_INVESTOR:"VALUE_INVESTOR",BANKER:"BANKER",CRISIS_INVESTOR:"CRISIS_TRADER",MACRO_STRATEGIST:"VALUE_INVESTOR",INDUSTRIALIST:"CORPORATE_RAIDER",COMMODITY_TRADER:"SPECULATOR",RISK_OFFICER:"BANKER"};
export function createLegacyCharacter(profile:{id:string;displayName:string;avatarId:string;archetypeId:string;level:number;xp:number}):Character{return createCharacter({id:`character-${profile.id}`,name:profile.displayName||"Investor",avatar:profile.avatarId||"male-industrialist-01",archetype:legacyMap[profile.archetypeId]??"VALUE_INVESTOR",traits:["DEEP_RESEARCH","CALCULATED_RISK"],weakness:"RISK_AVERSE",level:Math.max(1,profile.level||1),xp:Math.max(0,profile.xp||0)})}
