import type{CharacterModifier,CharacterSkillDefinition,CharacterStatKey}from"./models";
const add=(stat:CharacterStatKey,value:number,source:string):CharacterModifier=>({category:stat.toUpperCase()as CharacterModifier["category"],stat,operation:"ADD",value,source});
export const CHARACTER_SKILLS:CharacterSkillDefinition[]=[
 {id:"TAPE_READER_I",name:"Tape Reader I",description:"Train price-action recognition. Stacks with the natural Tape Reader trait.",category:"TRADING",tier:1,creditCost:150,requiredLevel:1,modifiers:[add("trading",3,"Tape Reader I")]},
 {id:"TAPE_READER_II",name:"Tape Reader II",description:"Refine volume and reversal reading without removing uncertainty.",category:"TRADING",tier:2,creditCost:350,requiredLevel:3,prerequisites:["TAPE_READER_I"],modifiers:[add("trading",5,"Tape Reader II")]},
 {id:"SHORT_SPECIALIST",name:"Short Specialist",description:"Improves discipline around bearish positions.",category:"TRADING",tier:2,creditCost:300,requiredLevel:2,allowedArchetypes:["SPECULATOR","CRISIS_TRADER"],modifiers:[add("trading",4,"Short Specialist"),add("risk",-1,"Short Specialist")]},
 {id:"EXECUTION_DISCIPLINE",name:"Execution Discipline",description:"Reduces avoidable execution mistakes.",category:"TRADING",tier:1,creditCost:180,requiredLevel:1,modifiers:[add("trading",2,"Execution Discipline"),add("risk",2,"Execution Discipline")]},
 {id:"SOURCE_EVALUATION",name:"Source Evaluation",description:"Improves judgment of incomplete sources.",category:"INFORMATION",tier:1,creditCost:150,requiredLevel:1,modifiers:[add("information",3,"Source Evaluation")]},
 {id:"DEEP_RESEARCH_SKILL",name:"Deep Research",description:"Develops research craft beyond natural aptitude.",category:"INFORMATION",tier:2,creditCost:300,requiredLevel:2,prerequisites:["SOURCE_EVALUATION"],modifiers:[add("information",5,"Deep Research skill")]},
 {id:"RUMOR_ANALYST",name:"Rumor Analyst",description:"Improves skepticism toward unconfirmed claims.",category:"INFORMATION",tier:2,creditCost:280,requiredLevel:2,prerequisites:["SOURCE_EVALUATION"],modifiers:[add("information",3,"Rumor Analyst"),add("risk",2,"Rumor Analyst")]},
 {id:"INTELLIGENCE_NETWORK",name:"Intelligence Network",description:"Combines research practice with source access.",category:"INFORMATION",tier:3,creditCost:500,requiredLevel:5,prerequisites:["DEEP_RESEARCH_SKILL"],modifiers:[add("information",5,"Intelligence Network"),add("network",3,"Intelligence Network")]},
 {id:"BANKER_CONTACTS",name:"Banker Contacts",description:"Builds reliable financing relationships.",category:"NETWORK",tier:1,creditCost:170,requiredLevel:1,modifiers:[add("network",3,"Banker Contacts")]},
 {id:"PRESS_NETWORK",name:"Press Network",description:"Expands access to financial reporters.",category:"NETWORK",tier:1,creditCost:180,requiredLevel:1,modifiers:[add("network",2,"Press Network"),add("information",2,"Press Network")]},
 {id:"INDUSTRIAL_CONNECTIONS",name:"Industrial Connections",description:"Creates operating-company relationships.",category:"NETWORK",tier:2,creditCost:300,requiredLevel:3,prerequisites:["BANKER_CONTACTS"],modifiers:[add("network",4,"Industrial Connections"),add("influence",2,"Industrial Connections")]},
 {id:"INSTITUTIONAL_NETWORK",name:"Institutional Network",description:"Connects capital providers across institutions.",category:"NETWORK",tier:3,creditCost:480,requiredLevel:5,prerequisites:["BANKER_CONTACTS","PRESS_NETWORK"],modifiers:[add("network",5,"Institutional Network"),add("reputation",3,"Institutional Network")]},
 {id:"MARGIN_DISCIPLINE",name:"Margin Discipline",description:"Improves awareness of leveraged exposure.",category:"RISK",tier:1,creditCost:160,requiredLevel:1,modifiers:[add("risk",3,"Margin Discipline")]},
 {id:"LIQUIDITY_RESERVE",name:"Liquidity Reserve",description:"Rewards preserving room to respond.",category:"RISK",tier:1,creditCost:190,requiredLevel:1,modifiers:[add("risk",3,"Liquidity Reserve")]},
 {id:"CRISIS_DISCIPLINE",name:"Crisis Discipline",description:"Supports decisions during stressed markets.",category:"RISK",tier:2,creditCost:320,requiredLevel:3,prerequisites:["MARGIN_DISCIPLINE"],modifiers:[add("risk",5,"Crisis Discipline")]},
 {id:"DRAWDOWN_RECOVERY",name:"Drawdown Recovery",description:"Strengthens measured recovery after losses.",category:"RISK",tier:3,creditCost:450,requiredLevel:5,prerequisites:["CRISIS_DISCIPLINE"],modifiers:[add("risk",4,"Drawdown Recovery"),add("trading",2,"Drawdown Recovery")]},
 {id:"TRUSTED_OPERATOR",name:"Trusted Operator",description:"Builds credibility through consistent conduct.",category:"REPUTATION",tier:1,creditCost:180,requiredLevel:1,modifiers:[add("reputation",4,"Trusted Operator")]},
 {id:"INSTITUTIONAL_STANDING",name:"Institutional Standing",description:"Turns credibility into institutional influence.",category:"REPUTATION",tier:2,creditCost:340,requiredLevel:3,prerequisites:["TRUSTED_OPERATOR"],modifiers:[add("reputation",5,"Institutional Standing"),add("influence",3,"Institutional Standing")]},
 {id:"OFFICE_MANAGEMENT",name:"Office Management",description:"Prepares the character for a future organization.",category:"EMPIRE",tier:1,creditCost:220,requiredLevel:2,allowedArchetypes:["CORPORATE_RAIDER","BANKER"],modifiers:[add("influence",3,"Office Management")]},
 {id:"BRANCH_PLANNING",name:"Branch Planning",description:"Plans future expansion without implementing offices yet.",category:"EMPIRE",tier:2,creditCost:420,requiredLevel:4,prerequisites:["OFFICE_MANAGEMENT"],modifiers:[add("influence",4,"Branch Planning"),add("network",2,"Branch Planning")]}
];
