import type{DivisionId}from"../financial-house/models";import type{Employee,EmployeeRoleId}from"./models";
export const ROLE_COMPATIBILITY:Record<DivisionId,EmployeeRoleId[]>={TRADING:["TRADER","BROKER","DIVISION_MANAGER"],RESEARCH:["ANALYST","RESEARCHER","DIVISION_MANAGER"],BONDS:["BANKER","ANALYST","BROKER","DIVISION_MANAGER"],FOREIGN_EXCHANGE:["FX_SPECIALIST","TRADER","DIVISION_MANAGER"],COMMODITIES:["COMMODITY_SPECIALIST","TRADER","DIVISION_MANAGER"],CORPORATE_FINANCE:["BANKER","RELATIONSHIP_MANAGER","DIVISION_MANAGER"],INVESTMENT_BANKING:["BANKER","ANALYST","DIVISION_MANAGER"],WEALTH_MANAGEMENT:["RELATIONSHIP_MANAGER","ANALYST","DIVISION_MANAGER"],PRIVATE_BANKING:["RELATIONSHIP_MANAGER","BANKER","DIVISION_MANAGER"]};
export function roleLabel(role:EmployeeRoleId,year:number){const early:Partial<Record<EmployeeRoleId,string>>={TRADER:"Securities Trader",ANALYST:"Market Analyst",RESEARCHER:"Research Clerk",BANKER:"Banking Partner",RELATIONSHIP_MANAGER:"Private Client Officer",FX_SPECIALIST:"Foreign Exchange Dealer",DIVISION_MANAGER:"Department Head",EXECUTIVE:"Managing Partner"},modern:Partial<Record<EmployeeRoleId,string>>={ANALYST:"Research Analyst",BANKER:"Investment Banker"};return(year<1950?early:year>=2000?modern:{} as Partial<Record<EmployeeRoleId,string>>)[role]??role.replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
export function seniorityLabel(s:Employee["seniority"],year:number){if(year<1950)return({JUNIOR:"Clerk",ASSOCIATE:"Associate",SENIOR:"Senior",DIRECTOR:"Principal",PARTNER:"Partner"}as const)[s];return s[0]+s.slice(1).toLowerCase()}
export const CANDIDATES:Employee[]=[
{id:"ada-hart",name:"Ada Hart",role:"ANALYST",seniority:"ASSOCIATE",skills:{trading:42,research:82,network:55,leadership:45,dealmaking:38},salary:18000,signingCost:12000,loyalty:72,reputation:48,traits:["ANALYTICAL"],homeCenterId:"NEW_YORK",status:"AVAILABLE",availableFromYear:1890},
{id:"thomas-reed",name:"Thomas Reed",role:"TRADER",seniority:"SENIOR",skills:{trading:85,research:48,network:62,leadership:55,dealmaking:42},salary:26000,signingCost:18000,loyalty:64,reputation:61,traits:["DISCIPLINED"],homeCenterId:"NEW_YORK",status:"AVAILABLE",availableFromYear:1890},
{id:"edward-blythe",name:"Edward Blythe",role:"BANKER",seniority:"DIRECTOR",skills:{trading:45,research:58,network:84,leadership:76,dealmaking:88},salary:42000,signingCost:30000,loyalty:58,reputation:76,traits:["WELL_CONNECTED","AMBITIOUS"],homeCenterId:"LONDON",status:"AVAILABLE",availableFromYear:1890},
{id:"clara-weiss",name:"Clara Weiss",role:"RESEARCHER",seniority:"SENIOR",skills:{trading:35,research:91,network:52,leadership:61,dealmaking:44},salary:28000,signingCost:20000,loyalty:81,reputation:65,traits:["ANALYTICAL","LOYAL"],homeCenterId:"FRANKFURT",status:"AVAILABLE",availableFromYear:1900},
{id:"henry-falk",name:"Henry Falk",role:"DIVISION_MANAGER",seniority:"DIRECTOR",skills:{trading:62,research:65,network:71,leadership:90,dealmaking:70},salary:45000,signingCost:35000,loyalty:69,reputation:78,traits:["DISCIPLINED"],homeCenterId:"NEW_YORK",status:"AVAILABLE",availableFromYear:1900},
{id:"mei-tan",name:"Mei Tan",role:"FX_SPECIALIST",seniority:"SENIOR",skills:{trading:78,research:64,network:82,leadership:57,dealmaking:63},salary:38000,signingCost:26000,loyalty:73,reputation:68,traits:["WELL_CONNECTED"],homeCenterId:"HONG_KONG",status:"AVAILABLE",availableFromYear:1950}
];
