import{describe,expect,it}from"vitest";import{advanceRound,benchmarkValue,createNewGame,startGame}from"./engine/game-engine";import{EVENTS,GREAT_CRASH,NEWS}from"./episodes/prologue";import{getAvailableEvents,getAvailableNews,getHistoricalContext,getMarketRegime,getMarketSentiment}from"./intelligence/service";import{migrateSavegame}from"./persistence/browser";import{evaluateRisk}from"./risk/service";import{changeStrategy,createStrategy}from"./strategy/service";import{executeTrade}from"./trading/service";import type{GameState}from"./types";
describe("Sprint 1 systems",()=>{
it("hides future events, news, and context",()=>{const d="1929-09-01";expect(getAvailableEvents(d).some(e=>e.id==="black-thursday")).toBe(false);expect(getAvailableNews(d).some(n=>n.id==="n-thursday")).toBe(false);expect(getHistoricalContext(EVENTS.find(e=>e.id==="black-thursday")!,d)).toBeUndefined()});
it("maps dates to regimes and known sentiment",()=>{expect(getMarketRegime("1929-10-24").internalRegime).toBe("PANIC");expect(getMarketSentiment("1932-05-01")).toBe("NEGATIVE");expect(getMarketRegime("1933-05-01").internalRegime).toBe("RECOVERY")});
it("records strategy changes",()=>{const s=startGame(createNewGame());const n=changeStrategy(s,createStrategy("DEFENSIVE"),"Reduce risk");expect(n.strategyProfile.id).toBe("DEFENSIVE");expect(n.strategyHistory[0].previousStrategy.id).toBe("BALANCED")});
it("detects strategy violations",()=>{let s:GameState=startGame(createNewGame());s=executeTrade(s,"BUY","industrials",700);s={...s,strategyProfile:createStrategy("CAPITAL_PRESERVATION")};const alerts=evaluateRisk(s);expect(alerts.some(a=>a.type==="LOW_CASH")).toBe(true);expect(alerts.some(a=>a.type==="HIGH_EQUITY_EXPOSURE")).toBe(true)});
it("creates a complete round briefing",()=>{let s=startGame(createNewGame());s={...s,currentDate:"1929-10-22",roundNumber:94,seenEvents:EVENTS.filter(e=>e.date<="1929-10-22").map(e=>e.id),seenNews:NEWS.filter(n=>n.availableFrom<="1929-10-22").map(n=>n.id)};const r=advanceRound(s);expect(r.summary.date).toBe("1929-10-29");expect(r.summary.newEvents.some(e=>e.id==="black-thursday")).toBe(true);expect(r.summary.newNews.length).toBeGreaterThan(0)});
it("calculates a deterministic benchmark",()=>{expect(benchmarkValue(20,4)).toBe(benchmarkValue(20,4));expect(benchmarkValue(20,4)).not.toBe(100000)});
it("defines the required objectives",()=>{expect(GREAT_CRASH.objectives.map(o=>o.type)).toEqual(expect.arrayContaining(["SURVIVE","CAPITAL_PRESERVATION","MAX_DRAWDOWN","MIN_CASH","OUTPERFORM_BENCHMARK"]))});
it("migrates v1 without losing portfolio data",()=>{const v2=createNewGame();const v1={...v2,schemaVersion:1,marketState:{prices:v2.marketState.prices,previousPrices:v2.marketState.previousPrices}};delete(v1 as Partial<GameState>).strategyProfile;delete(v1 as Partial<GameState>).riskAlerts;const migrated=migrateSavegame(v1);expect(migrated.schemaVersion).toBe(2);expect(migrated.cash).toBe(v2.cash);expect(migrated.strategyProfile.id).toBe("BALANCED")});
});
