import{describe,expect,it}from"vitest";import{CHALLENGES}from"./campaign/challenges";import{completeCareerEpisode,createCareer,carryCapital}from"./campaign/career";import{EPISODE_REGISTRY,getEpisode}from"./campaign/episodes";import{ERAS}from"./campaign/eras";import{migrateToV3}from"./campaign/persistence";import{gradeForScore,levelForXp,resultFor}from"./campaign/progression";import{advanceDate,effectiveGranularity}from"./campaign/rounds";import{advanceRound,completeGame,createNewGame,startGame}from"./engine/game-engine";
describe("Sprint 2 campaign systems",()=>{
 it("registers all eras without exposing future event data",()=>{expect(ERAS).toHaveLength(18);expect(ERAS[0].id).toBe("E01");expect(JSON.stringify(ERAS)).not.toContain("Black Tuesday")});
 it("starts a career in 1900 with only E01 unlocked",()=>{const c=createCareer("2026-01-01T00:00:00.000Z");expect(c.capital).toBe(100000);expect(c.currentEraId).toBe("E01");expect(c.eraProgress.filter(e=>e.status==="UNLOCKED").map(e=>e.eraId)).toEqual(["E01"])});
 it("unlocks the next era and carries capital",()=>{const c=createCareer();const n=completeCareerEpisode(c,{episodeId:"panic-1907",score:800,grade:"A",xpEarned:400,endingCapital:120000,totalReturn:20,maxDrawdown:8,objectivesCompleted:3,completedAt:"1908-12-31"});expect(n.eraProgress[0].status).toBe("COMPLETED");expect(n.eraProgress[1].status).toBe("UNLOCKED");expect(n.capital).toBe(120000);expect(carryCapital(130000,"FIXED")).toBe(100000)});
 it("supports day week and month date advancement plus crisis override",()=>{expect(advanceDate("1900-01-01","DAY")).toBe("1900-01-02");expect(advanceDate("1900-01-01","WEEK")).toBe("1900-01-08");expect(advanceDate("1900-01-01","MONTH")).toBe("1900-02-01");expect(effectiveGranularity(getEpisode("great-crash"),"1929-10-24")).toBe("DAY")});
 it("provides three playable episode slices and six challenges",()=>{expect(Object.keys(EPISODE_REGISTRY)).toEqual(expect.arrayContaining(["panic-1907","great-crash","oil-shock"]));expect(CHALLENGES).toHaveLength(6);expect(CHALLENGES.filter(c=>c.status==="AVAILABLE")).toHaveLength(3)});
 it("starts and advances every playable episode",()=>{for(const id of Object.keys(EPISODE_REGISTRY)){const game=startGame(createNewGame(7,id));const next=advanceRound(game).state;expect(next.currentDate>game.currentDate).toBe(true);expect(Object.keys(next.marketState.prices)).toEqual(expect.arrayContaining(getEpisode(id).availableAssets))}});
 it("calculates bounded scores grades xp and results",()=>{const done=completeGame(startGame(createNewGame()));const result=resultFor(done);expect(result.score).toBeGreaterThanOrEqual(0);expect(result.score).toBeLessThanOrEqual(1000);expect(gradeForScore(900)).toBe("S");expect(levelForXp(9999)).toBe(10)});
 it("migrates a v2 standalone episode into a v3 archive",()=>{const game=createNewGame();const save=migrateToV3({schemaVersion:2,gameState:game});expect(save.schemaVersion).toBe(3);expect(save.activeEpisode?.episodeId).toBe("great-crash");expect(save.career).toBeNull()});
 it("contains bank holiday and market closed special rules",()=>{const rules=Object.values(EPISODE_REGISTRY).flatMap(e=>e.specialRules??[]).map(r=>r.type);expect(rules).toEqual(expect.arrayContaining(["BANK_HOLIDAY","MARKET_CLOSED"]))});
});
