import{describe,expect,it,vi}from"vitest";import{EcbProvider,ProviderChain,WorldBankProvider}from"./providers";import{fogOfHistory,HistoricalDataCache,validateObservations}from"./pipeline";import{SOURCES}from"./registry";import type{HistoricalDataProvider,NormalizedObservation}from"./models";
const row=(date:string,available=date):NormalizedObservation=>({seriesId:"x",observationDate:date,releaseDate:available,availableFrom:available,value:1,unit:"index",frequency:"MONTHLY",dataType:"HISTORICAL",sourceId:"world-bank",sourceSeriesId:"X",quality:"HIGH",provenance:{sourceId:"world-bank",providerName:"World Bank",sourceSeriesId:"X",sourceLabel:"WDI",retrievedAt:"2026-01-01",attribution:"World Bank",transformationNotes:[]}});
describe("Sprint 5 historical data",()=>{
it("registers evaluated sources and keeps restricted providers inactive",()=>{expect(SOURCES.map(x=>x.id)).toEqual(expect.arrayContaining(["fred","world-bank","ecb","alpha-vantage","curated","simulated"]));expect(SOURCES.find(x=>x.id==="alpha-vantage")?.active).toBe(false);expect(SOURCES.find(x=>x.id==="world-bank")?.licenseName).toContain("CC BY")});
it("normalizes World Bank observations",async()=>{const fetcher=vi.fn().mockResolvedValue({ok:true,json:async()=>[{},[{indicator:{id:"NY.GDP"},date:"1973",value:42}]]}),p=new WorldBankProvider("USA",fetcher as never),rows=await p.getObservations("NY.GDP");expect(rows[0]).toMatchObject({observationDate:"1973-12-31",dataType:"HISTORICAL",quality:"HIGH",sourceId:"world-bank"})});
it("normalizes ECB SDMX CSV",async()=>{const fetcher=vi.fn().mockResolvedValue({ok:true,text:async()=>"TIME_PERIOD,OBS_VALUE\n1973-01,7.5"}),p=new EcbProvider(fetcher as never),rows=await p.getObservations("EXR:TEST");expect(rows[0]).toMatchObject({observationDate:"1973-01",value:7.5,sourceId:"ecb"})});
it("validates ordering and rejects duplicates",()=>{expect(validateObservations([row("1973-02-01"),row("1973-01-01")])[0].observationDate).toBe("1973-01-01");expect(()=>validateObservations([row("1973-01-01"),row("1973-01-01")])).toThrow(/Duplicate/)});
it("caches provider output",async()=>{const provider={getObservations:vi.fn().mockResolvedValue([row("1973-01-01")])}as unknown as HistoricalDataProvider,cache=new HistoricalDataCache();await cache.get(provider,"x");await cache.get(provider,"x");expect(provider.getObservations).toHaveBeenCalledOnce()});
it("falls back when a provider is unavailable",async()=>{const bad={getObservations:vi.fn().mockRejectedValue(new Error("offline"))}as unknown as HistoricalDataProvider,good={getObservations:vi.fn().mockResolvedValue([row("1973-01-01")])}as unknown as HistoricalDataProvider;expect(await new ProviderChain([bad,good]).observations("x")).toHaveLength(1)});
it("enforces observation, release, and vintage boundaries",()=>{const rows=[row("1929-08-01","1929-09-01"),row("1929-09-01","1929-10-01")];expect(fogOfHistory(rows,"1929-09-01")).toHaveLength(1);expect(fogOfHistory(rows,"1929-09-01")[0].observationDate).toBe("1929-08-01")});
});
