import type{DataType}from"../types";export type SourceType="CENTRAL_BANK"|"GOVERNMENT"|"INTERNATIONAL_ORGANIZATION"|"EXCHANGE"|"MARKET_DATA_PROVIDER"|"ARCHIVE"|"ACADEMIC"|"CURATED_INTERNAL";export type DataQuality="VERIFIED"|"HIGH"|"MEDIUM"|"LOW"|"UNKNOWN";export interface SourceDefinition{id:string;name:string;provider:string;sourceType:SourceType;baseUrl?:string;documentationUrl?:string;licenseName?:string;licenseUrl?:string;commercialUseStatus:"ALLOWED_WITH_ATTRIBUTION"|"RESTRICTED"|"SERIES_DEPENDENT"|"UNKNOWN";attributionRequirement:string;apiKeyRequired:boolean;rateLimitNotes:string;historicalCoverage:string;assetCoverage:string;geographicCoverage:string;dataLatency:string;supportsVintageData:boolean;active:boolean;notes:string}
export interface DataProvenance{sourceId:string;providerName:string;sourceSeriesId:string;sourceLabel:string;sourceUrl?:string;documentationUrl?:string;retrievedAt:string;license?:string;attribution:string;transformationNotes:string[]}
export interface NormalizedObservation{seriesId:string;observationDate:string;releaseDate?:string;availableFrom:string;value:number;unit:string;frequency:"DAILY"|"WEEKLY"|"MONTHLY"|"QUARTERLY"|"ANNUAL";dataType:DataType;sourceId:string;sourceSeriesId:string;vintageDate?:string;realTimeStart?:string;realTimeEnd?:string;quality:DataQuality;provenance:DataProvenance}
export interface HistoricalPriceBar{assetId:string;date:string;open?:number;high?:number;low?:number;close:number;adjustedClose?:number;volume?:number;currency:string;frequency:"DAILY"|"WEEKLY"|"MONTHLY";adjustment:"RAW"|"ADJUSTED";dataType:DataType;sourceId:string;quality:DataQuality}
export interface HistoricalDataset{id:string;name:string;providerId:string;series:string[];coverageStart:string;coverageEnd:string;frequency:string;dataType:DataType;provenance:DataProvenance;quality:DataQuality;lastUpdated:string;version:string}
export interface SeriesMetadata{id:string;name:string;unit:string;frequency:string;coverageStart?:string;coverageEnd?:string;sourceId:string}
export interface HistoricalDataProvider{getSeriesMetadata(seriesId:string):Promise<SeriesMetadata>;getObservations(seriesId:string):Promise<NormalizedObservation[]>;getObservationAt(seriesId:string,date:string):Promise<NormalizedObservation|undefined>;getObservationsBetween(seriesId:string,start:string,end:string):Promise<NormalizedObservation[]>;getLatestAvailableObservation(seriesId:string,availableAt:string):Promise<NormalizedObservation|undefined>;getVintageObservation?(seriesId:string,observationDate:string,vintageDate:string):Promise<NormalizedObservation|undefined>;getAssetHistory(assetId:string,start:string,end:string):Promise<HistoricalPriceBar[]>;healthCheck():Promise<{ok:boolean;message:string}>}
export interface AssetAvailabilityPeriod{assetId:string;availableFrom:string;availableUntil?:string;tradable:boolean;shortable:boolean;reason?:string}
export interface CorporateAction{assetId:string;date:string;type:"STOCK_SPLIT"|"DIVIDEND"|"MERGER"|"DELISTING"|"REORGANIZATION";ratio?:number;amount?:number;currency?:string;sourceId:string;dataType:DataType}
