import { ERAS } from "./eras";
import { levelForXp } from "./progression";
import type { AppSaveV3, CapitalCarryoverMode, CareerState, EpisodeResult } from "./types";

export const DEFAULT_STATS={episodesStarted:0,episodesCompleted:0,challengesCompleted:0,trades:0,bestScore:0,totalXp:0,highestCapital:100000,largestDrawdown:0,shortTrades:0,profitableShortTrades:0,shortPnL:0,borrowFeesPaid:0,marginCalls:0,forcedCovers:0,maxGrossExposure:0};
export function createCareer(now=new Date().toISOString()):CareerState{return{id:`career-${Date.now()}`,createdAt:now,updatedAt:now,currentEraId:"E01",capital:100000,carryoverMode:"FULL",difficulty:"HISTORIAN",eraProgress:ERAS.map((e,i)=>({eraId:e.id,status:i===0?"UNLOCKED":"LOCKED"})),level:1,xp:0,completedEpisodeIds:[]}}
export function carryCapital(ending:number,mode:CapitalCarryoverMode){return mode==="FULL"?Math.max(1000,ending):mode==="NORMALIZED"?100000+Math.max(-25000,Math.min(50000,ending-100000)*.5):100000}
export function completeCareerEpisode(career:CareerState,result:EpisodeResult):CareerState{const currentIndex=ERAS.findIndex(e=>e.id===career.currentEraId),next=ERAS[currentIndex+1],xp=career.xp+result.xpEarned;return{...career,updatedAt:new Date().toISOString(),currentEraId:next?.id??career.currentEraId,capital:carryCapital(result.endingCapital,career.carryoverMode),xp,level:levelForXp(xp),completedEpisodeIds:[...new Set([...career.completedEpisodeIds,result.episodeId])],eraProgress:career.eraProgress.map((p,i)=>i===currentIndex?{...p,status:"COMPLETED",bestScore:Math.max(p.bestScore??0,result.score),bestGrade:result.grade,completedAt:result.completedAt}:i===currentIndex+1?{...p,status:"UNLOCKED"}:p)}}
export function applyResult(save:AppSaveV3,result:EpisodeResult,isChallenge=false):AppSaveV3{const career=save.career&&!isChallenge?completeCareerEpisode(save.career,result):save.career,now=new Date().toISOString(),achievements=save.achievements.map(a=>({...a,unlockedAt:a.unlockedAt??(a.id==="first-era"&&!isChallenge||a.id==="capital-keeper"&&result.endingCapital>=100000||a.id==="crisis-tested"&&isChallenge?now:undefined)}));return{...save,career,achievements,stats:{...save.stats,episodesCompleted:save.stats.episodesCompleted+(isChallenge?0:1),challengesCompleted:save.stats.challengesCompleted+(isChallenge?1:0),bestScore:Math.max(save.stats.bestScore,result.score),totalXp:(career?.xp??save.stats.totalXp),highestCapital:Math.max(save.stats.highestCapital,result.endingCapital),largestDrawdown:Math.max(save.stats.largestDrawdown,result.maxDrawdown)},updatedAt:now}}
