import { ASSETS, GREAT_CRASH } from "../episodes/prologue";
import type { Episode, HistoricalEvent, NewsItem, Objective } from "../types";

const objectives=(capital:number):Objective[]=>[
 {id:"survive",type:"SURVIVE",title:"Reach the end",description:"Complete the historical episode.",target:1,required:true,status:"ACTIVE"},
 {id:"capital",type:"CAPITAL_PRESERVATION",title:"Preserve capital",description:`Finish with at least ${capital*0.75}.`,target:capital*0.75,required:false,status:"ACTIVE"},
 {id:"drawdown",type:"MAX_DRAWDOWN",title:"Control drawdown",description:"Keep maximum drawdown below 40%.",target:40,required:false,status:"ACTIVE"}
];
const event=(episodeId:string,id:string,date:string,title:string,summary:string,severity:HistoricalEvent["severity"]="ELEVATED"):HistoricalEvent=>({id,episodeId,date,title,summary,category:"MARKET",severity,dataType:"HISTORICAL",relatedAssets:[],relatedSectors:[]});
const report=(episodeId:string,id:string,date:string,headline:string,summary:string,sentiment:NewsItem["sentiment"]):NewsItem=>({id,episodeId,date,availableFrom:date,headline,summary,category:"MARKET",importance:sentiment==="PANIC"?5:3,sentiment,dataType:"RECONSTRUCTED",relatedAssets:[],relatedEvents:[],sourceLabel:"Reconstructed period report"});

export const PANIC_1907:Episode={id:"panic-1907",eraId:"E01",name:"Panic of 1907",subtitle:"1906–1908",startDate:"1906-01-01",endDate:"1908-12-31",startingCapital:100000,baseCurrency:"USD",roundGranularity:"MONTH",description:"Navigate a speculative boom, trust-company runs, and a private banking rescue.",historicalSummary:"A playable reconstruction of the Panic of 1907. Prices are simulated; dated events are historical.",availableAssets:["industrials","banking","railroads","gold","bonds"],objectives:objectives(100000),events:[event("panic-1907","sf-quake","1906-04-18","San Francisco earthquake","Insurance claims and reconstruction needs pressure international gold flows."),event("panic-1907","knickerbocker","1907-10-22","Knickerbocker Trust suspends operations","A failed rescue attempt accelerates depositor runs.","SYSTEMIC"),event("panic-1907","pool-rescue","1907-11-03","Bankers organize a rescue pool","Private capital is assembled to restore market liquidity.","CRISIS"),event("panic-1907","recovery-1908","1908-06-01","Confidence begins to recover","Financial conditions stabilize as reform discussions continue.")],news:[report("panic-1907","p07-growth","1906-01-01","Industrial demand remains firm","Rail and industrial activity support market confidence.","POSITIVE"),report("panic-1907","p07-trust","1907-10-22","Trust-company run shocks New York","Depositors seek cash as confidence breaks.","PANIC"),report("panic-1907","p07-rescue","1907-11-04","Financiers coordinate emergency support","A rescue pool supplies critical liquidity.","NERVOUS")],marketRegimes:[{id:"p07-expansion",startDate:"1906-01-01",endDate:"1907-06-30",internalRegime:"EXPANSION",displayLabel:"Industrial expansion"},{id:"p07-slowdown",startDate:"1907-07-01",endDate:"1907-09-30",internalRegime:"SLOWDOWN",displayLabel:"Credit tightening"},{id:"p07-panic",startDate:"1907-10-01",endDate:"1907-12-31",internalRegime:"PANIC",displayLabel:"Trust-company panic"},{id:"p07-recovery",startDate:"1908-01-01",endDate:"1908-12-31",internalRegime:"RECOVERY",displayLabel:"Uneven recovery"}],difficulty:"HISTORIAN",dataType:"RECONSTRUCTED",completionRules:{endDate:"1908-12-31"},crisisWindows:[{startDate:"1907-10-20",endDate:"1907-11-10",granularity:"DAY",label:"Banking Panic"}],specialRules:[{type:"BANK_HOLIDAY",startDate:"1907-10-24",endDate:"1907-10-24",reason:"Emergency bank closures interrupt financial activity.",blockedAssetClasses:["EQUITY"]}]};

export const OIL_SHOCK:Episode={id:"oil-shock",eraId:"E10",name:"Oil Shock",subtitle:"1972–1975",startDate:"1972-01-01",endDate:"1975-12-31",startingCapital:100000,baseCurrency:"USD",roundGranularity:"MONTH",description:"Manage inflation, an oil embargo, recession, and a deep equity bear market.",historicalSummary:"A playable reconstruction of the 1973–74 oil shock. Market prices are simulated.",availableAssets:["industrials","banking","energy","automotive","gold","bonds"],objectives:objectives(100000),events:[event("oil-shock","bretton-end","1973-03-01","Currency system shifts","Exchange-rate instability adds to inflation pressure."),event("oil-shock","oil-embargo","1973-10-17","Oil embargo begins","Energy supply restrictions cause a rapid price shock.","SYSTEMIC"),event("oil-shock","recession-74","1974-01-01","Recession takes hold","Inflation and contracting activity pressure businesses.","CRISIS"),event("oil-shock","recovery-75","1975-04-01","Recovery signals emerge","Demand and market confidence begin to stabilize.")],news:[report("oil-shock","oil-early","1972-01-01","Expansion continues amid rising prices","Growth remains positive while inflation draws attention.","POSITIVE"),report("oil-shock","oil-embargo-report","1973-10-17","Energy supplies disrupted","Fuel prices and shortages threaten production.","PANIC"),report("oil-shock","oil-recession-report","1974-01-02","Stagflation deepens","Weak output combines with persistent inflation.","NEGATIVE")],marketRegimes:[{id:"oil-expansion",startDate:"1972-01-01",endDate:"1973-09-30",internalRegime:"EXPANSION",displayLabel:"Inflationary expansion"},{id:"oil-panic",startDate:"1973-10-01",endDate:"1974-03-31",internalRegime:"PANIC",displayLabel:"Energy shock"},{id:"oil-contraction",startDate:"1974-04-01",endDate:"1974-12-31",internalRegime:"CONTRACTION",displayLabel:"Stagflation recession"},{id:"oil-recovery",startDate:"1975-01-01",endDate:"1975-12-31",internalRegime:"RECOVERY",displayLabel:"Early recovery"}],difficulty:"HISTORIAN",dataType:"RECONSTRUCTED",completionRules:{endDate:"1975-12-31"},crisisWindows:[{startDate:"1973-10-15",endDate:"1973-11-15",granularity:"WEEK",label:"Oil Embargo"}]};

const crash:Episode={...GREAT_CRASH,eraId:"E04",subtitle:"1928–1933",availableAssets:["industrials","banking","railroads","gold","bonds"],crisisWindows:[{startDate:"1929-10-24",endDate:"1929-11-02",granularity:"DAY",label:"Wall Street Crash"}],specialRules:[{type:"MARKET_CLOSED",startDate:"1933-03-06",endDate:"1933-03-09",reason:"The national bank holiday closes financial institutions.",blockedAssetClasses:["EQUITY","BOND"]}]};
export const EPISODE_REGISTRY:Record<string,Episode>={"panic-1907":PANIC_1907,"great-crash":crash,"oil-shock":OIL_SHOCK};
export const PLAYABLE_EPISODES=Object.values(EPISODE_REGISTRY);
export function getEpisode(id:string){const episode=EPISODE_REGISTRY[id];if(!episode)throw new Error(`Unknown episode: ${id}`);return episode}
export function getEpisodeAssets(id:string){const episode=getEpisode(id);return ASSETS.filter(a=>episode.availableAssets.includes(a.id))}
