import type { GameState } from "../types";
import { runAgentRuntime } from "../agents/runtime";
import { upgradeAdvancedState } from "../advanced-trading/service";
import { createCareer, DEFAULT_STATS } from "./career";
import type { AppSaveV3 } from "./types";
import { createPendingProfile, defaultHistory } from "../identity/service";
import { CURRENT_DATASET_VERSION } from "../historical-data/pipeline";
import { defaultEraIdentityState } from "../identity/evolution";

export const SAVE_V3_KEY="wallstreet-time-machine:save:v3";
const LEGACY_V2_KEY="wallstreet-time-machine:save:v2";
export function createAppSave():AppSaveV3{return{schemaVersion:3,historicalDatasetVersion:CURRENT_DATASET_VERSION,investorProfile:null,characterHistory:defaultHistory(),investorLegacy:null,eraIdentityState:defaultEraIdentityState(),career:null,activeEpisode:null,episodeSaves:{},challengeSaves:{},agentSettings:{enabled:true,alerts:true,detailLevel:"STANDARD",conflictAlerts:true,scenarioAnalysis:true,enabledAgents:{MARKET:true,MACRO:true,RISK:true,NEWS:true,COMMODITY:true,STRATEGY:true}},agentAnalyses:[],agentSignalHistory:[],agentDisagreements:[],agentMemory:[],watchlist:[],playerNotes:[],acknowledgedAlerts:[],intelligenceAlerts:[],seenIndicatorReleases:[],achievements:[{id:"first-era",title:"Time Traveler",description:"Complete your first career era."},{id:"capital-keeper",title:"Capital Keeper",description:"Finish an episode above starting capital."},{id:"crisis-tested",title:"Crisis Tested",description:"Complete a crisis challenge."}],stats:{...DEFAULT_STATS},settings:{difficulty:"HISTORIAN",carryoverMode:"FULL",reducedMotion:false,animationSpeed:"NORMAL",masterAudio:false,uiSounds:true,marketSounds:true,newsSounds:true,ambience:false,cinematicIntros:true,breakingNewsOverlays:true,tickerMotion:true,intelligenceDetail:"STANDARD"},updatedAt:new Date().toISOString()}}
export function migrateToV3(value:unknown):AppSaveV3{if(value&&typeof value==="object"&&(value as {schemaVersion?:number}).schemaVersion===3){const incoming=value as AppSaveV3;const defaults=createAppSave();const profile=incoming.investorProfile??(incoming.career?createPendingProfile(incoming.career):null);return{...defaults,...incoming,activeEpisode:incoming.activeEpisode?upgradeAdvancedState(incoming.activeEpisode):null,episodeSaves:Object.fromEntries(Object.entries(incoming.episodeSaves??{}).map(([k,v])=>[k,upgradeAdvancedState(v)])),challengeSaves:Object.fromEntries(Object.entries(incoming.challengeSaves??{}).map(([k,v])=>[k,upgradeAdvancedState(v)])),investorProfile:profile,characterHistory:incoming.characterHistory??defaultHistory(),eraIdentityState:incoming.eraIdentityState??defaultEraIdentityState(),stats:{...defaults.stats,...incoming.stats},settings:{...defaults.settings,...incoming.settings},agentSettings:{...defaults.agentSettings,...incoming.agentSettings,enabledAgents:{...defaults.agentSettings.enabledAgents,...incoming.agentSettings?.enabledAgents}}}}const save=createAppSave();const wrapped=value as {schemaVersion?:number;gameState?:GameState}|null;if(wrapped?.schemaVersion===2&&wrapped.gameState)return{...save,activeEpisode:upgradeAdvancedState(wrapped.gameState),episodeSaves:{[wrapped.gameState.episodeId]:upgradeAdvancedState(wrapped.gameState)}};throw new Error("Unsupported savegame")}
export function loadAppSave(){const raw=localStorage.getItem(SAVE_V3_KEY);if(raw){try{return migrateToV3(JSON.parse(raw))}catch{return createAppSave()}}const old=localStorage.getItem(LEGACY_V2_KEY);if(old){try{const migrated=migrateToV3(JSON.parse(old));saveAppSave(migrated);return migrated}catch{return createAppSave()}}return createAppSave()}
export function saveAppSave(save:AppSaveV3){localStorage.setItem(SAVE_V3_KEY,JSON.stringify({...save,updatedAt:new Date().toISOString()}))}
export function newCareerSave(){const save=createAppSave(),career=createCareer();return{...save,career,investorProfile:createPendingProfile(career),updatedAt:new Date().toISOString()}}
export function storeEpisode(save:AppSaveV3,state:GameState,challengeId?:string):AppSaveV3{
  const run=runAgentRuntime(state,save.watchlist,save.playerNotes,save.agentSettings.enabledAgents);
  const analyses=[...save.agentAnalyses,...run.analyses].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i).slice(-120);
  const signals=[...save.agentSignalHistory,...run.analyses.flatMap(x=>x.signals)].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i).slice(-120);
  const agentMemory=run.analyses.map(current=>({agentId:current.agentId,previousAnalyses:analyses.filter(x=>x.agentId===current.agentId).slice(-20),recentSignalChanges:current.signals.map(x=>`${x.type}:${x.status}`),recentConfidenceChanges:[current.confidence],recentDisagreements:run.disagreements.filter(x=>x.agentIds.includes(current.agentId)).map(x=>x.id)}));
  return{...save,activeEpisode:state,episodeSaves:challengeId?save.episodeSaves:{...save.episodeSaves,[state.episodeId]:state},challengeSaves:challengeId?{...save.challengeSaves,[challengeId]:state}:save.challengeSaves,agentAnalyses:analyses,agentSignalHistory:signals,agentDisagreements:run.disagreements,agentMemory,stats:{...save.stats,trades:Object.values({...save.episodeSaves,[state.episodeId]:state}).reduce((n,s)=>n+s.tradeHistory.length,0),shortTrades:Object.values({...save.episodeSaves,[state.episodeId]:state}).reduce((n,s)=>n+s.tradeHistory.filter(t=>t.side==="SHORT").length,0),profitableShortTrades:Object.values({...save.episodeSaves,[state.episodeId]:state}).reduce((n,s)=>n+s.tradeHistory.filter(t=>t.side==="COVER"&&(t.reason!=="FORCED_LIQUIDATION")).length,0),shortPnL:state.shortPositions.reduce((n,p)=>n+p.realizedPnL+p.unrealizedPnL,0),borrowFeesPaid:state.borrowFeesPaid,marginCalls:state.marginCalls.length,forcedCovers:state.forcedCovers,maxGrossExposure:Math.max(save.stats.maxGrossExposure??0,state.maxGrossExposure)},updatedAt:new Date().toISOString()}
}
