import type{FinancialCenterDefinition}from"./models";const req=(cash:number,credits:number,rep:number,skill:"BRANCH_PLANNING"|"OFFICE_MANAGEMENT"="BRANCH_PLANNING")=>[{type:"office_level",value:3},{type:"reputation",value:rep},{type:"character_level",value:4},{type:"skill",skillId:skill},{type:"cash",value:cash},{type:"credits",value:credits}]as FinancialCenterDefinition["requirements"];
export const FINANCIAL_CENTERS:FinancialCenterDefinition[]=[
{id:"NEW_YORK",name:"New York",country:"United States",availableFromYear:1792,specialties:["Equity Markets","Corporate Finance","Industrial Markets"],description:"The existing headquarters and primary American securities market.",requirements:[],cashCost:0,creditCost:0,modifiers:[{category:"regionalInsight",value:5,scope:"US_MARKETS",description:"Improved knowledge of American industrial and equity markets."}]},
{id:"LONDON",name:"London",country:"United Kingdom",availableFromYear:1801,specialties:["Foreign Exchange","Government Bonds","International Trade","Commodities"],description:"A global center for trade finance, sovereign securities and commodities.",requirements:req(250000,1000,60),cashCost:250000,creditCost:1000,modifiers:[{category:"informationAccess",value:8,scope:"INTERNATIONAL_TRADE",description:"Earlier access to international trade sources."},{category:"regionalInsight",value:6,scope:"COMMODITIES",description:"Improved commodity market context without revealing truth states."}]},
{id:"FRANKFURT",name:"Frankfurt",country:"Germany",availableFromYear:1585,specialties:["Banking","Industry","Corporate Finance","European Markets"],description:"A continental banking and industrial finance center.",requirements:req(220000,900,58),cashCost:220000,creditCost:900,modifiers:[{category:"sourceAccess",value:7,scope:"BANKING",description:"Improved access to banking and industrial sources."}]},
{id:"ZURICH",name:"Zurich",country:"Switzerland",availableFromYear:1877,specialties:["Wealth","Private Capital","Gold","Defensive Capital"],description:"A defensive capital center with deep private banking traditions.",requirements:req(240000,950,65),cashCost:240000,creditCost:950,modifiers:[{category:"researchQuality",value:5,scope:"DEFENSIVE_CAPITAL",description:"Sharper defensive-capital research ranges."}]},
{id:"PARIS",name:"Paris",country:"France",availableFromYear:1724,specialties:["Industry","Luxury","Government Finance"],description:"A major market for industry and state-linked finance.",requirements:req(210000,850,56,"OFFICE_MANAGEMENT"),cashCost:210000,creditCost:850,modifiers:[{category:"informationAccess",value:6,scope:"EUROPEAN_INDUSTRY",description:"Improved access to continental industrial reports."}]},
{id:"CHICAGO",name:"Chicago",country:"United States",availableFromYear:1848,specialties:["Futures","Agriculture","Commodities"],description:"America's center for agricultural contracts and commodity risk.",requirements:req(180000,750,52,"OFFICE_MANAGEMENT"),cashCost:180000,creditCost:750,modifiers:[{category:"regionalInsight",value:8,scope:"AGRICULTURE",description:"Improved agricultural and commodity insight."}]},
{id:"TOKYO",name:"Tokyo",country:"Japan",availableFromYear:1878,specialties:["Industrial Groups","Foreign Exchange","Asian Markets"],description:"An Asian center for industrial capital and exchange markets.",requirements:[...req(350000,1400,72),{type:"office_level",value:4}],cashCost:350000,creditCost:1400,modifiers:[{category:"sourceAccess",value:7,scope:"ASIA",description:"Improved access to Japanese industrial sources."}]},
{id:"HONG_KONG",name:"Hong Kong",country:"Hong Kong",availableFromYear:1891,specialties:["International Trade","Property","Asian Capital"],description:"A gateway for regional trade and cross-border capital.",requirements:[...req(375000,1500,75),{type:"office_level",value:4},{type:"existing_branch",centerId:"LONDON"}],cashCost:375000,creditCost:1500,modifiers:[{category:"rumorFreshness",value:1,scope:"ASIA_TRADE",description:"Regional trade rumors arrive one step fresher, never automatically true."}]}
];
export function specialtiesForEra(center:FinancialCenterDefinition,year:number){if(center.id==="LONDON")return year<1980?["Government Bonds","International Trade","Commodities","Foreign Securities"]:year<2000?["Foreign Exchange","Eurobonds","Investment Banking","Commodities"]:["Foreign Exchange","Global Capital Markets","Asset Management","Investment Banking"];if(center.id==="TOKYO"&&year<1950)return["Industrial Finance","Government Securities","Foreign Exchange"];if(center.id==="HONG_KONG"&&year<1950)return["Shipping","International Trade","Foreign Exchange"];return center.specialties}
