import type{DivisionDefinition,DivisionId,HouseLevel}from"./models";
const r=(house:number,office:number,cash:number,credits:number,skill?:"OFFICE_MANAGEMENT"|"BRANCH_PLANNING")=>[{type:"house_level",value:house},{type:"office_level",value:office},...(skill?[{type:"skill"as const,skillId:skill}]:[]),{type:"cash",value:cash},{type:"credits",value:credits}]as DivisionDefinition["requirements"];
export const HOUSE_LEVELS:{level:HouseLevel;name:string}[]=[{level:1,name:"Brokerage"},{level:2,name:"Securities Firm"},{level:3,name:"Investment House"},{level:4,name:"International Financial House"},{level:5,name:"Global Financial Institution"}];
export const DIVISIONS:DivisionDefinition[]=[
{id:"TRADING",availableFromYear:1792,requirements:[],cashCost:0,creditCost:0,specialties:["Securities execution","Market intelligence"],modifiers:[{category:"regionalInsight",value:3,scope:"MARKETS",description:"Improves market context without guaranteeing profitable execution."}],synergies:[{centerId:"NEW_YORK",modifier:{category:"regionalInsight",value:2,scope:"US_MARKETS",description:"New York strengthens domestic securities intelligence."}}]},
{id:"RESEARCH",availableFromYear:1800,requirements:[...r(1,1,25000,150),{type:"skill",skillId:"DEEP_RESEARCH_SKILL"}],cashCost:25000,creditCost:150,specialties:["Company reports","Market intelligence"],modifiers:[{category:"researchQuality",value:8,scope:"INVESTIGATION",description:"Improves investigation quality without revealing hidden truth."}],synergies:[{centerId:"FRANKFURT",modifier:{category:"researchQuality",value:3,scope:"EUROPEAN_INDUSTRY",description:"Frankfurt improves continental industrial research."}}]},
{id:"BONDS",availableFromYear:1792,requirements:[...r(2,2,80000,350),{type:"skill",skillId:"BANKER_CONTACTS"}],cashCost:80000,creditCost:350,specialties:["Government finance","Credit markets"],modifiers:[{category:"informationAccess",value:6,scope:"BONDS",description:"Improves access to bond-market information."}],synergies:["NEW_YORK","LONDON","FRANKFURT"].map(centerId=>({centerId:centerId as "NEW_YORK",modifier:{category:"regionalInsight",value:3,scope:"BONDS",description:"A major banking center strengthens bond intelligence."}}))},
{id:"FOREIGN_EXCHANGE",availableFromYear:1800,requirements:[...r(2,2,100000,400,"BRANCH_PLANNING"),{type:"branch_any",centerIds:["LONDON","ZURICH"]}],cashCost:100000,creditCost:400,specialties:["Currency information","International markets"],modifiers:[{category:"informationAccess",value:6,scope:"CURRENCIES",description:"Improves international currency context; no FX engine is introduced."}],synergies:["LONDON","ZURICH","HONG_KONG","TOKYO"].map(centerId=>({centerId:centerId as "LONDON",modifier:{category:"regionalInsight",value:4,scope:"CURRENCIES",description:"The local currency market improves regional insight."}}))},
{id:"COMMODITIES",availableFromYear:1848,requirements:[...r(2,2,90000,350,"OFFICE_MANAGEMENT"),{type:"branch_any",centerIds:["CHICAGO","LONDON","HONG_KONG"]}],cashCost:90000,creditCost:350,specialties:["Supply intelligence","Futures preparation"],modifiers:[{category:"informationAccess",value:6,scope:"COMMODITIES",description:"Improves commodity and supply information."}],synergies:["CHICAGO","LONDON","HONG_KONG"].map(centerId=>({centerId:centerId as "CHICAGO",modifier:{category:"regionalInsight",value:4,scope:"COMMODITIES",description:"Local exchange access strengthens commodity intelligence."}}))},
{id:"CORPORATE_FINANCE",availableFromYear:1800,requirements:[...r(2,3,125000,500,"OFFICE_MANAGEMENT"),{type:"skill",skillId:"BANKER_CONTACTS"}],cashCost:125000,creditCost:500,specialties:["Capital raising","Corporate relationships"],modifiers:[{category:"sourceAccess",value:6,scope:"CORPORATE",description:"Prepares access to corporate financing opportunities."}],synergies:[{centerId:"NEW_YORK",modifier:{category:"reputationGain",value:3,scope:"CORPORATE",description:"New York strengthens corporate-finance standing."}}]},
{id:"INVESTMENT_BANKING",availableFromYear:1900,requirements:[...r(3,4,250000,900,"BRANCH_PLANNING"),{type:"division",divisionId:"CORPORATE_FINANCE"},{type:"reputation",value:65}],cashCost:250000,creditCost:900,specialties:["Offerings","Advisory preparation"],modifiers:[{category:"sourceAccess",value:8,scope:"DEALS",description:"Prepares future deal access without creating a deal engine."}],synergies:[{centerId:"LONDON",modifier:{category:"reputationGain",value:4,scope:"INTERNATIONAL_DEALS",description:"London strengthens international advisory standing."}}]},
{id:"WEALTH_MANAGEMENT",availableFromYear:1950,requirements:r(3,3,180000,650,"OFFICE_MANAGEMENT"),cashCost:180000,creditCost:650,specialties:["Managed capital","Client relationships"],modifiers:[{category:"sourceAccess",value:6,scope:"CLIENTS",description:"Prepares future managed-client access."}],synergies:[{centerId:"ZURICH",modifier:{category:"reputationGain",value:4,scope:"WEALTH",description:"Zurich strengthens wealth relationships."}}]},
{id:"PRIVATE_BANKING",availableFromYear:1800,requirements:[...r(3,3,200000,700,"BRANCH_PLANNING"),{type:"branch_any",centerIds:["ZURICH","LONDON"]}],cashCost:200000,creditCost:700,specialties:["Private capital","Relationship banking"],modifiers:[{category:"sourceAccess",value:7,scope:"PRIVATE_CLIENTS",description:"Prepares access to private capital relationships."}],synergies:["ZURICH","LONDON","NEW_YORK"].map(centerId=>({centerId:centerId as "ZURICH",modifier:{category:"reputationGain",value:4,scope:"PRIVATE_CLIENTS",description:"The center strengthens private-client access."}}))}
];
export function divisionName(id:DivisionId,year:number){const names:Record<DivisionId,string>={TRADING:year<1950?"Securities Trading":"Trading",RESEARCH:year<1950?"Research & Market Intelligence":"Research",BONDS:"Bonds",FOREIGN_EXCHANGE:"Foreign Exchange",COMMODITIES:"Commodities",CORPORATE_FINANCE:"Corporate Finance",INVESTMENT_BANKING:year<1980?"Merchant & Corporate Finance":year<2000?"Investment Banking":"Investment Banking & Capital Markets",WEALTH_MANAGEMENT:year<1980?"Investment Counsel":"Wealth Management",PRIVATE_BANKING:year<1950?"Private Client Banking":"Private Banking"};return names[id]}
