import{FINANCIAL_CENTERS}from"../expansion/catalog";import{activeBranchModifiers}from"../expansion/service";import type{BranchModifier,ExpansionState,FinancialCenterId}from"../expansion/models";import{DIVISIONS}from"./catalog";import{FinancialHouseSchema}from"./schema";import type{BranchDivisionAssignment,DivisionId,DivisionRequirement,FinancialHouse,HouseContext}from"./models";
export function houseNameFor(playerName:string){const clean=playerName.trim()||"Investor",surname=clean.split(/\s+/).at(-1)!;return`${surname} & Co.`}
export function createFinancialHouse(playerName="Investor",foundedYear=1900):FinancialHouse{return{id:"player-financial-house",name:houseNameFor(playerName),headquartersCenterId:"NEW_YORK",foundedYear,level:1,prestige:0,divisions:[{id:"TRADING",level:1,status:"ACTIVE",openedYear:foundedYear,openedRound:0}],branchAssignments:[{centerId:"NEW_YORK",divisionId:"TRADING"}]}}
export function normalizeFinancialHouse(value:unknown,playerName="Investor",foundedYear=1900){const parsed=FinancialHouseSchema.safeParse(value);return parsed.success?parsed.data as FinancialHouse:createFinancialHouse(playerName,foundedYear)}
export function requirementMet(r:DivisionRequirement,h:FinancialHouse,c:HouseContext){switch(r.type){case"house_level":return h.level>=r.value;case"office_level":return c.officeLevel>=r.value;case"character_level":return c.character.level>=r.value;case"reputation":return c.character.stats.reputation>=r.value;case"credits":return c.character.credits>=r.value;case"cash":return c.cash>=r.value;case"year":return c.year>=r.value;case"skill":return c.character.unlockedSkills.includes(r.skillId);case"branch_any":return r.centerIds.some(x=>c.activeBranches.includes(x));case"division":return h.divisions.some(x=>x.id===r.divisionId&&x.status==="ACTIVE")}}
export function canOpenDivision(h:FinancialHouse,id:DivisionId,c:HouseContext){const d=DIVISIONS.find(x=>x.id===id);if(!d)return{allowed:false,reasons:["unknown_division"]};if(h.divisions.some(x=>x.id===id))return{allowed:false,reasons:["already_active"]};if(c.year<d.availableFromYear)return{allowed:false,reasons:["era_locked"]};const reasons=d.requirements.filter(r=>!requirementMet(r,h,c)).map(r=>`requires_${r.type}`);return{allowed:reasons.length===0,reasons}}
export function openDivision(h:FinancialHouse,id:DivisionId,c:HouseContext){const check=canOpenDivision(h,id,c);if(!check.allowed)throw new Error(check.reasons.join(","));const d=DIVISIONS.find(x=>x.id===id)!,house=FinancialHouseSchema.parse({...h,divisions:[...h.divisions,{id,status:"ACTIVE",level:1,openedYear:c.year,openedRound:c.round}],prestige:Math.min(100,h.prestige+5)}) as FinancialHouse;return{house,cash:c.cash-d.cashCost,credits:c.character.credits-d.creditCost}}
export function locationActive(centerId:FinancialCenterId,h:FinancialHouse,expansion:ExpansionState){return centerId===h.headquartersCenterId||expansion.branches.some(x=>x.centerId===centerId&&x.status==="ACTIVE")}
export function locationCapacity(centerId:FinancialCenterId,h:FinancialHouse,expansion:ExpansionState){if(centerId===h.headquartersCenterId)return 2+h.level;const branch=expansion.branches.find(x=>x.centerId===centerId);return branch?branch.level*2:0}
export function canAssignDivision(h:FinancialHouse,expansion:ExpansionState,assignment:BranchDivisionAssignment){if(!h.divisions.some(x=>x.id===assignment.divisionId&&x.status==="ACTIVE"))return{allowed:false,reason:"division_inactive"};if(!FINANCIAL_CENTERS.some(x=>x.id===assignment.centerId))return{allowed:false,reason:"invalid_center"};if(!locationActive(assignment.centerId,h,expansion))return{allowed:false,reason:"branch_inactive"};if(h.branchAssignments.some(x=>x.centerId===assignment.centerId&&x.divisionId===assignment.divisionId))return{allowed:false,reason:"already_assigned"};if(h.branchAssignments.filter(x=>x.centerId===assignment.centerId).length>=locationCapacity(assignment.centerId,h,expansion))return{allowed:false,reason:"location_capacity"};return{allowed:true}}
export function assignDivision(h:FinancialHouse,expansion:ExpansionState,assignment:BranchDivisionAssignment){const check=canAssignDivision(h,expansion,assignment);if(!check.allowed)throw new Error(check.reason);return FinancialHouseSchema.parse({...h,branchAssignments:[...h.branchAssignments,assignment]}) as FinancialHouse}
export function locationSynergies(h:FinancialHouse){return h.branchAssignments.flatMap(a=>DIVISIONS.find(x=>x.id===a.divisionId)?.synergies.filter(x=>x.centerId===a.centerId).map(x=>x.modifier)??[])}
export function activeHouseModifiers(h:FinancialHouse,expansion:ExpansionState):BranchModifier[]{const division=h.divisions.filter(x=>x.status==="ACTIVE").flatMap(x=>DIVISIONS.find(d=>d.id===x.id)?.modifiers??[]);return[...activeBranchModifiers(expansion),...division,...locationSynergies(h)]}
export function investigationQualityBonus(h:FinancialHouse,expansion:ExpansionState){return activeHouseModifiers(h,expansion).filter(x=>x.category==="researchQuality"&&x.scope==="INVESTIGATION").reduce((n,x)=>n+x.value,0)}
export function updateHouseName(h:FinancialHouse,name:string){return FinancialHouseSchema.parse({...h,name:name.trim()}) as FinancialHouse}
