import type{Character}from"../character-foundation/models";import{getEffectiveCharacterStats}from"../character-foundation/service";import{INFORMATION_SOURCES}from"./catalog";import{InformationItemSchema,InformationStateSchema}from"./schema";import type{InformationFreshness,InformationItem,InformationSource,InformationState,InvestigationResult,ReliabilityDisplay,RumorTruthState}from"./models";
const clamp=(n:number,min=0,max=100)=>Math.max(min,Math.min(max,Math.round(n)));const has=(c:Character,id:Character["unlockedSkills"][number])=>c.unlockedSkills.includes(id);
export function deterministicUnit(seed:number){let x=seed|0;x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967295}
export function getRumorTruthState(seed:number):RumorTruthState{const n=deterministicUnit(seed);return n<.38?"TRUE":n<.72?"PARTIALLY_TRUE":"FALSE"}
export function isInformationSourceAvailableInEra(source:InformationSource,year:number){return year>=source.minYear&&year<=(source.maxYear??9999)}
export function getInformationAge(item:InformationItem,currentRound:number){return Math.max(0,currentRound-item.createdRound)}
export function isInformationExpired(item:InformationItem,currentRound:number){return item.status==="EXPIRED"||item.expiresRound!==undefined&&currentRound>item.expiresRound}
export function getInformationFreshness(item:InformationItem,currentRound:number):InformationFreshness{if(isInformationExpired(item,currentRound))return"EXPIRED";const age=getInformationAge(item,currentRound);return age<=1?"FRESH":age<=3?"RECENT":age<=6?"AGING":age<=10?"STALE":"EXPIRED"}
export function getDisplayedInformationReliability(character:Character,item:InformationItem):ReliabilityDisplay{const source=INFORMATION_SOURCES.find(x=>x.id===item.sourceId),stats=getEffectiveCharacterStats(character),skillPrecision=(has(character,"SOURCE_EVALUATION")?8:0)+(has(character,"RUMOR_ANALYST")&&item.type==="RUMOR"?7:0)+(item.investigationCount*8),traitPrecision=character.traits.includes("DEEP_RESEARCH")?3:0,precision=clamp(18+Math.floor(stats.information/8)+skillPrecision+traitPrecision,18,42),center=clamp(item.displayedReliability??Math.round((item.baseReliability+(source?.baseReliability??50))/2)+(stats.information-50)/12,8,92),half=Math.max(4,Math.round((100-precision)/8)),min=clamp(center-half,4,92),max=clamp(center+half,8,96);return{value:center,min,max,label:center>=70?"HIGH":center>=45?"MEDIUM":"LOW",precision}}
export function canAccessInformation(character:Character,item:InformationItem,year:number){const source=INFORMATION_SOURCES.find(x=>x.id===item.sourceId);if(!source||!isInformationSourceAvailableInEra(source,year))return false;if(source.category==="BANKER"&&source.accessLevel>0&&!has(character,"BANKER_CONTACTS")&&getEffectiveCharacterStats(character).network<65)return false;return source.accessLevel<=Math.floor(getEffectiveCharacterStats(character).network/35)+(has(character,"INTELLIGENCE_NETWORK")?1:0)}
export function visibleInformation(state:InformationState,input:{character:Character;year:number;currentDate:string;currentRound:number;episodeId?:string}){return state.items.filter(item=>item.availableFromDate<=input.currentDate&&item.createdRound<=input.currentRound&&(!item.episodeId||item.episodeId===input.episodeId)&&canAccessInformation(input.character,item,input.year))}
export function canAcquireInformation(item:InformationItem,cash:number){return item.status==="AVAILABLE"&&!isInformationExpired(item,item.createdRound)&&cash>=item.acquisitionCost}
export function acquireInformation(item:InformationItem,cash:number){if(item.status!=="AVAILABLE")throw new Error("Information is not available");if(cash<item.acquisitionCost)throw new Error("Insufficient cash");return{information:InformationItemSchema.parse({...item,status:"ACQUIRED"}),cash:cash-item.acquisitionCost,cost:item.acquisitionCost}}
export function canInvestigateInformation(item:InformationItem,cash:number,currentRound:number){return["ACQUIRED","INVESTIGATING"].includes(item.status)&&!isInformationExpired(item,currentRound)&&cash>=item.investigationCost}
export function investigateInformation(character:Character,item:InformationItem,cash:number,currentRound:number,seed=item.seed):InvestigationResult{if(isInformationExpired(item,currentRound))throw new Error("Information has expired");if(!["ACQUIRED","INVESTIGATING"].includes(item.status))throw new Error("Acquire information before investigating");if(cash<item.investigationCost)throw new Error("Insufficient cash");const stats=getEffectiveCharacterStats(character),quality=clamp(Math.round(stats.information*.55+stats.network*.2)+(has(character,"DEEP_RESEARCH_SKILL")?14:0)+(has(character,"RUMOR_ANALYST")?8:0)+Math.floor(deterministicUnit(seed+item.investigationCount)*15)),truth=item.rumorTruthState??getRumorTruthState(seed),conclusive=quality>=72,status=conclusive?(truth==="FALSE"?"DISPROVED":"CONFIRMED"):"INVESTIGATING",details=item.details.slice(0,Math.min(item.details.length,1+Math.floor(quality/45))),displayedReliability=truth==="FALSE"?clamp(item.baseReliability-quality/3,10,80):truth==="TRUE"?clamp(item.baseReliability+quality/4,20,90):clamp(item.baseReliability+quality/10,15,88),information=InformationItemSchema.parse({...item,status,investigationCount:item.investigationCount+1,revealedDetails:[...new Set([...item.revealedDetails,...details])],displayedReliability});return{character,information,cash:cash-item.investigationCost,cost:item.investigationCost,quality}}
export function ignoreInformation(item:InformationItem){return InformationItemSchema.parse({...item,status:"IGNORED"})}
export function expireInformation(state:InformationState,currentRound:number):InformationState{return InformationStateSchema.parse({...state,items:state.items.map(item=>isInformationExpired(item,currentRound)&&!["CONFIRMED","DISPROVED"].includes(item.status)?{...item,status:"EXPIRED"}:item),lastProcessedRound:Math.max(state.lastProcessedRound,currentRound)})}
export function updateInformationItem(state:InformationState,item:InformationItem):InformationState{return InformationStateSchema.parse({...state,items:state.items.map(x=>x.id===item.id?item:x)})}
export function getRoundBriefingInformation(state:InformationState,input:{character:Character;year:number;currentDate:string;currentRound:number;episodeId?:string}){const importance={CRITICAL:4,HIGH:3,MEDIUM:2,LOW:1},impact={EXTREME:4,HIGH:3,MEDIUM:2,LOW:1};return visibleInformation(state,input).filter(x=>!["IGNORED","EXPIRED","UNSEEN"].includes(x.status)).sort((a,b)=>(importance[b.importance]+impact[b.marketImpact])-(importance[a.importance]+impact[a.marketImpact])).slice(0,6)}
